import csv
import random
import re

# Categories and example templates
categories = {
    "Drug Trafficking": [
        "delivery of {drug}",
        "{drug} for delivery",
        "distributing {drug}",
        "exchanging {drug} for {financial_gain}",
        "distribution of {drug}",
        "{charged_with} a felony, drug trafficking",
        "{charged_with} dealing in {drug}",
        "{charged_with} {drug} dealing",
        "trafficking {drug}",
        "{drug} trafficking - felony",
        "{conspiracy_to} traffic {drug}",
        "transporting {drug}",
        "deliver or {distribute} {drug}",
        "{charged_with} a misdemeanor, selling of {drug}",
        "{drug} for sale",
        "{possessing} {drug} for sale",
        "{possessing} a {schedule_drug} substance with intent to {distribute}",
        "{charged_with} {possessing} {drug} for sale",
        "possession of {drug} with intent to {distribute}",
        "possession of {drug} with intent",
        "possess {drug} intention to {distribute}",
        "carrying {drug} with intention to {distribute}",
        "{possessing} {drug} with purpose to {distribute}",
        "transport {drug} intent to {distribute}, {numeric_quantity} grams or more",
        "{charged_with} transport of {drug}",
        "selling {drug} by the {place}",
        "carrying {drug} for sale at a {place}",
        "planning to sell {drug} for profit",
        "{charged_with} illegally smuggling {drug} to sell on market",
        "{charged_with} manufacturing {drug}",
        "{charged_with} making {drug} for sale",
        "{possessing} precursors to make {drug}",
        "{conspiracy_to} {distribute} {drug} onto grounds of a {prison}",
        "{improper} conveyance of {drug} in a {prison}",
        "{prison} inmate trafficked {drug} - felony",
        "{charged_with} operation of a clandestine {drug} laboratory",
        "{charged_with} cultivating {drug}",
        # Edge case
        "{charged_with} trafficking offenses",
        "{charged_with} a trafficking offense",
        "sell or deliver within {numeric_quantity} yards of a {place}",
        "{possessing} a controlled substance, {drug}, with intent to deliver {numeric_quantity} grams or more",
    ],
    "Drug Possession": [
        "consume {drug} for personal use",
        "consumption of {drug}",
        "{charged_with} a misdemeanor, {possessing} {drug} for consumption",
        "smoking {drug} by the {place}",
        "{charged_with} consuming {drug}",
        "possess {drug} for personal use",
        "possess {drug} - felony",
        "{possessing} {drug}",
        "{improper} possession of a {drug}",
        "received {drug}",
        "{charged_with} receiving {drug}",
        "receipt of a {drug}",
        "{drug} possession",
        "possession of {drug}",
        "in possession of {drug}",
        "under influence of {drug}",
        "taking {drug}, a minor misdemeanor",
        "use of {drug} - felony",
        "using {drug}",
        "carrying {drug}",
        "{charged_with} being under the influence of {drug}",
        "intoxicated by {drug} while working",
        "found at the {place} intoxicated by {drug}",
        "{possessing} {numeric_quantity} grams of {drug}",
        "{charged_with} {drug} possession - {numeric_quantity} grams",
        "{drug} possession",
        "{charged_with} {possessing} a schedule 3 controlled substance",
        "{under_the_influence} of a substance that is not alcohol",
        "{possessing} a controlled dangerous substance",
        "{possessing} {drug} in a drug-free zone",
        "attempted possession of {drug}",
        "minor misdemeanor {drug} possession",
        "{possessing} a {schedule_drug} substance",
        "{conspiracy_to} to unlawfully possess a {drug}",
        #Larceny Edge Case
        "{charged_with} simple possession of {schedule_drug}",
        # Drug Trafficking Edge Case
        "possession with intent to use {drug} but not {distribute} it",
        "simple possession or casual exchange of {drug}",
        # Weapons Offense Edge Case
        "possess {drug} while armed, a felony",
    ],
    "Unspecified Drug Offense": [
        "possession of drug paraphernalia",
        "in possession of drug related equipment",
        "hypodermic needle syringe",
        "{charged_with} possession of a hypodermic needle",
        "{possessing} a hypodermic syringe",
        "{possessing} drug paraphernalia",
        "manufacturing drug paraphernalia",
        "using drug paraphernalia",
        "{drug} paraphernalia",
        "using drug paraphernalia at a {place}",
        "{charged_with} using drug paraphernalia",
        "{possessing} a injection syringe",
        "using materials that make drugs",
        "{charged_with} possessing paraphernalia for drugs",
        "{charged_with} unspecified {drug} offense",
        "{charged_with} a controlled substance violation"
        "{charged_with} a misdemeanor of {possessing} drug paraphernalia",
        "{charged_with} inhalation of vapors or volatile chemical",
    ],
    "Unspecified Manslaughter": [
        "killed another person in an incident that remains unclear",
        "responsible for an accidental death without clear intent",
        "involved in a fatal situation where cause was uncertain",
        "killed person in unclear circumstances"
        "{charged_with} manslaughter, felony",
    ],
    "Intimidation (Not Witness)": [
        "stalking a {victim}",
        "{charged_with} stalking",
        "{charged_with} intimidation",
        "{severe} intimidation",
        "intimidation of a {victim}",
        "{intimidating} a {victim}",
        "{charged_with} a felony, {intimidating} a {victim}",
        "{charged_with} {intimidating} a {victim} who is not a witness",
        "{intimidating} a {victim} {without} a financial motive",
        "{intimidating} a {victim} to instill fear",
        "used force or threats to intimidate a victim",
        "made threatening statements to a {victim}",
        "{charged_with} blackmailing a person",
        "{charged_with} blackmailing {without} demanding money",
        "{charged_with} blackmailing {without} {financial_gain} involved",
        "using {intimidating} language to {family_member}",
        "{charged_with} making threats to an individual",
        "{charged_with} menacing behavior towards a {victim} with credible threat of violence",
        "{charged_with} threatening violence",
        "{conspiracy_to} intimidate a {victim}",
        "{charged_with} making a terroristic threat of a {family_member}",
        "making a terroristic threat to a {victim}",
        "{charged_with} making a threat against the life of a {victim}",
        "threaten with intent to terrorize a {family_member}",
        "{charged_with} threatening to commit a crime",
        # Forcible sex offense edge case
        "{charged_with} coercion that was sexually motivated",
        # Assault edge case
        "threaten or intimidate with injury",
        "threaten or intimidate with {assault}",
        # Edge case
        "threatened a judge, prosecutor or {officer}",
        "made threats to kill a {family_member}",
    ],
    "Intimidating a Witness": [
        "{charged_with} {intimidating} a witness",
        "{severe} intimidation of a court witness",
        "{charged_with} intimidation of a witness during a legal proceeding",
        "{intimidating} a witness {without} a financial motive",
        "{charged_with} {intimidating} a witness to instill fear",
        "{charged_with} threatened a witness to prevent them from testifying",
        "used coercion to influence the testimony of a witness",
        "made threats to intimidate someone into silence during an investigation",
        "{intimidating} a witness",
        "{charged_with} a felony, witness intimidation",
        "threatening victim to affect testimony",
        "{conspiracy_to} intimidate a witness",
        "pressured a witness to change their statement",
        "warned a witness with harm if they spoke in court",
        "attempted to bribe a witness to remain silent",
        "coerced a {victim} to withdraw a complaint",
        "harassed a potential witness at {place}",
        "stalked a witness to deter them from testifying",
        "sent {intimidating} messages to a trial witness",
        "displayed a {weapon} while confronting a witness",
        "threatened witness's family to discourage cooperation",
        "offered money to a witness for false testimony",
        "{intimidating} a key witness in a criminal case",
        "attempted to suborn perjury by intimidation",
        "forced a witness to provide misleading statements",
        "accused of {intimidating} a witness into non-cooperation"
    ],
    "Extortion": [
        "{charged_with} extortion",
        "{conspiracy_to} extort",
        "{severe} extortion",
        "{improper} extortion",
        "extorting a {victim}",
        "{conspiracy_to} commit a felony, extorting a {victim}",
        "threatened to release damaging information unless paid",
        "{charged_with} having blackmailed someone for {financial_gain}",
        "{charged_with} blackmail for {financial_gain}",
        "{charged_with} using threats to obtain {financial_gain}",
        "intimidating a {victim} for the purpose of {financial_gain}",
        "extracted money from a {victim} through threats",
        "{improper} demand of hush money",
        "forced someone to hand over property through threats",
        "demanded payment from {victim} in exchange for withholding incriminating photos",
        "coerced a {victim} into transferring funds under duress",
        "extorted local businesses for protection fees",
        "pressured a {victim} to pay hush money",
        "made menacing phone calls demanding cash",
        "claimed physical harm would come if money was not paid",
        "threatened property damage in exchange for ransom",
        "attempted to extort a wealthy {victim}",
        "threatened public exposure of embarrassing details for {financial_gain}",
        "extracted money through repeated threats of violence"
    ],
    "Burglary": [
        "{charged_with} burglary",
        "{charged_with} burglary - felony",
        "burglary of a {motor_vehicle}",
        "{conspiracy_to} commit burglary",
        "{charged_with} breaking and entering",
        "broke into a house and stole a {stolen_property}",
        "forced entry into a building to take {stolen_property}",
        "{improper} entry into a {motor_vehicle}",
        "breaking and entering a {motor_vehicle} by a {place}",
        "{charged_with} forcing entry into a {motor_vehicle}",
        "{charged_with} entering a {motor_vehicle} with intent to commit theft",
        "{improper} entry into a building",
        "caught breaking into a private property to steal {stolen_property}",
        "{charged_with} a misdemeanor, second-degree burglary for entering a residence unlawfully",
        "{charged_with} first-degree burglary after entering a commercial building",
        "{charged_with} burglary after breaking into {place} and taking valuables",
        "entered a house through a window to steal {stolen_property}",
        "used force to gain entry into a home before stealing",
        "burglary incident involving forced entry through a locked door",
        "broke into a storage unit and took items without permission",
        "illegally entered a business at night to steal merchandise",
        "broke into a museum after hours and stole artifacts",
        "burglarized a secure facility and took {stolen_property}, felony",
        "trespassed into a residence to commit theft",
        "{charged_with} burglary after unauthorized entry into {place}",
        "illegally entered a school building with intent to steal",
        "attempted to pry open a locked door to steal property",
        "used tools to break into an apartment and steal electronics",
        "{charged_with} breaking and entering at {place} to commit theft, misdemeanor",
        "{charged_with} home invasion with intent to steal",
        "{charged_with} home invasion {minor_degree_level}",
        "{charged_with} home invasion but was not armed with a {weapon}",
    ],
    "Motor Vehicle Theft": [
        # Motor vehicle theft
        "theft of a {motor_vehicle}",
        "{motor_vehicle} theft",
        "{motor_vehicle} theft - felony",
        "operating a {motor_vehicle} without the owner's permission",
        "using a {motor_vehicle} without authorization of owner",
        "{improper} taking of {motor_vehicle}",
        "{conspiracy_to} steal a {motor_vehicle}",
        "{charged_with} a misdemeanor, carjacking",
        "{charged_with} carjacking {without} a weapon",
        "{charged_with} unauthorized use of a {motor_vehicle} belonging to a {victim}",
        "unauthorized operation of a {motor_vehicle}",
        "using a {motor_vehicle} without authorization",
        "{possessing} a stolen {motor_vehicle}",
        "stole a {motor_vehicle} from a parking lot",
        "found driving a stolen {motor_vehicle}",
        "attempting to take a {motor_vehicle} without permission",
        "{charged_with} unauthorized use of a {motor_vehicle}",
        "driving off in a {motor_vehicle} that was not theirs",
        "prowling around a {motor_vehicle} at night",
        "theft of a {motor_vehicle} from a dealership",
        "theft by unauthorized control",
        "caught with a stolen {motor_vehicle} in possession",
        "driving a stolen {motor_vehicle}, misdemeanor",
        "unlawfully driving away a {motor_vehicle}",
        "{charged_with} theft of means of transportation by control",
        # Burglary Edge cases
        "{charged_with} theft of a {motor_vehicle} {without} breaking into it",
        "theft of a {motor_vehicle} but no break in",
        # Kidnapping edge cases
        "taking a {motor_vehicle} but not kidnapping anyone",
        "took a {motor_vehicle} with nobody inside",
    ],
    "Larceny": [
        # General Property Theft
        "{conspiracy_to} commit larceny",
        "petty theft",
        "misdemeanor theft",
        "retail theft",
        "{charged_with} theft",
        "{charged_with} theft by receiving",
        "received stolen {stolen_property}",
        "{charged_with} theft",
        "{charged_with} larceny",
        "grand theft in the {minor_degree_level}",
        "{improper} taking",
        # Possessing stolen property
        "{possessing} stolen {stolen_property}",
        "{possessing} a stolen {payment_card}",
        "knowingly receiving or concealing {stolen_property}",
        # Stealing
        "theft of {payment_card}",
        "stole a {payment_card} from a {victim}",
        "shoplifting {stolen_property} from a {place}",
        "shoplifted {stolen_property} - felony",
        "grabbed {stolen_property} from a store shelf and ran",
        "took an unattended bag from a table at {place}",
        "pick pocketed {stolen_property} from a shopper",
        "{charged_with} retail theft after taking {stolen_property} from {place}",
        "{charged_with} theft of united states mail",
        "removed security tags from {stolen_property} and walked out of the store",
        "{charged_with} shoplifting after concealing items in clothing, misdemeanor",
        "{charged_with} grand theft for stealing high-value {stolen_property}",
        "took a package from someone's porch {without} permission",
        "{charged_with} petty theft after taking a bicycle from a park",
        "{charged_with} theft of services",
        "{charged_with} intent to obtain transportation without paying"
        "{failure to} pay for a taxi fare",
        "theft by taking over ${numeric_quantity} and under ${numeric_quantity}",
        "{charged_with} theft under ${numeric_quantity} at a {place}",
        "theft over ${numeric_quantity}",
        "{improper} taking of {stolen_property}",
        "{improper} appropriation of {stolen_property}",
        "{charged_with} taking of property - felony",
        "{failure to} pay for services",
        "alter price of {stolen_property} in a store, misdemeanor",
        "{improper} use of a universal product code label",
        "shoplift alter price, less than ${numeric_quantity}",
        # Fraud Larceny edge cases
        "{charged_with} theft {without} having deceived the person",
        "theft with no {deception} involved",
        "{charged_with} theft without {deception}",
        "unauthorized use of a {stolen_property} but did not sell it",
        "found with stolen {stolen_property} but did not covert it for {financial_gain}",
        "stole a {payment_card} but did not use it",
        # Edge Cases
        "{charged_with} theft of a {firearm}",
    ],
    "Other Property": [
        # Property Damage
        "vandalized a private property by spray painting",
        "using graffiti to deface a property",
        "destroyed public property",
        "damaged someone’s belongings during a dispute",
        "caused pecuniary loss",
        "causing damage to property",
        "{severe} vandalism",
        "{severe} property damage valued at $1000",
        "caused damage to {place} worth $300",
        "spraying graffiti",
        "{charged_with} possession of graffiti items",
        "{severe} damage to property"
        "fiddling with someone else's {vehicle_part}",
        "tampering with another {motor_vehicle}",
        "{charged_with} damaging a {vehicle_part}",
        "malicious injury to property under $ 1000",
        "malicious destruction of police property",
        "owner or tenant's {failure to} keep property clean",
        # Trespass
        "{charged_with} trespass",
        "{charged_with} trespassing",
        "{charged_with} trespassing on {place}",
        "criminal trespass on a private property",
        "{charged_with} criminal trespass on private property",
        "{charged_with} criminal mischief, misdemeanor",
        "{charged_with} tampering with property of a {victim}",
        "unauthorized entry into a private {place}",
        "{improper} entry into a private grounds, misdemeanor",
        "{improper} entry into school premises but did not break in",
        "{failure to} leave a private property when asked",
        "entered into a private property and {failure to} leave when notice given",
        "{charged_with} unauthorized entry to an operations area",
        "{charged_with} entering a non commercial dwelling",
        # Leaving the scene of accident
        "criminal mischief",
        "{charged_with} hit and run driving",
        "{charged_with} hit and run while causing property damage",
        "{charged_with} hit and run while damaging property",
        "hit and run attended {motor_vehicle}",
        "walking away from the scene of a {motor_vehicle} accident",
        "{charged_with} departing the scene of a {motor_vehicle} accident",
        "{charged_with} leaving the scene of an accident not having caused injury",
        "fled the scene of a crash with damage to {motor_vehicle} but no injuries",
        "{charged_with} leaving the scene after having caused property damage",
        "fleeing the scene of an accident after damaging a {motor_vehicle}",
        "{failure to} report an accident",
        "{failure to} stop at accident",
        # burglary tools
        "{charged_with} {possessing} burglary tools",
        "{possessing} tools for breaking and entering",
        "{possessing} instruments of a crime",
        "{charged_with} possession of instrument of crime",
        "{charged_with} possession of burglar's implements"
        "{possessing} shoplifting gear",
    ],
    "Court Violation": [
        # Court Appearance
        "{failure to} appear in court for a scheduled hearing",
        "{failure to} appear",
        "{failure to} appear {minor_degree_level}",
        "{failure to} appear for a court date",
        "{failure to} appear before court",
        "{charged_with} {failure to} make a court appearance",
        "{failure to} appear for booking or processing",
        "{failure to} appear on felony offense"
        "being in contempt of court",
        "contempt of court",
        "{failure to} appear on bond",
        # Registration
        "{failure to} register",
        "{failure to} comply with sexual offender registration"
        "predatory offender who knowingly violates registration"
        "{failure to} notify about address change",
        "{failure to} verify current address",
        "{failure to} register as a sex offender",
        "{charged_with} not registering as a sex offender",
        # Failure to pay
        "{failure to} pay court-mandated fines on time",
        "{failure to} pay court ordered restitution",
        "not paying bail as agreed in court",
        "bail jumping",
        # Court Order Violations
        "not abiding by court order",
        "contempt of court order",
        "{charged_with} violation of no contact order",
        "{charged_with} violation of order of protection",
        "{charged_with} being a community custody violator",
        "{charged_with} violation of civil protection order, felony",
        "{charged_with} violation of temporary protection order"
        "{charged_with} being a community custody or service violator"
        "{charged_with} violation of parks recreation and community service"
        "{failure to} comply with a restraining order issued by the court",
        "attempted to influence a witness in violation of court directives",
        "skipped scheduled drug testing mandated by the court",
        "{charged_with} {failure to} comply with court order",
        "{charged_with} {failure to} comply with a protective order",
        "disregarded court order to stay away from a victim",
        "violated terms of probation by missing check-ins",
        "criminal contempt of a domestic violence protective order",
        "{failure to} check in with a parole officer as required",
    ],
    "Non Support": [
        "{failure to} pay",
        "nonsupport",
        "{failure to} provide child support as ordered by the court",
        "{charged_with} {failure to} pay child support",
        "child support, {failure to} to pay",
        "{charged_with} non support",
        "{improper} nonsupport of child by parent",
    ],
    "Disorderly Conduct": [
        # Disorderly behaviour
        "{charged_with} breach of the peace",
        "{charged_with} disorderly conduct",
        "{improper} loitering and prowling",
        "{charged_with} causing a public {disturbance} at the {place}",
        "{failure to} to respect the lawful order",
        "{charged_with} {fighting} in a public {place}",
        "{charged_with} a misdemeanor, {fighting}",
        "{charged_with} inducing panic",
        "{charged_with} causing a {severe} {disturbance} in a public {place}",
        "participated in a {severe} {disturbance}",
        "{charged_with} {harassing} a {victim} in a public {place}",
        "{charged_with} {harassing}",
        "{charged_with} harassment in the {minor_degree_level}",
        "{charged_with} causing a noise violation",
        "{improper} nudity disturbing passersby",
        "{charged_with} public indecency",
        "{charged_with} indecent exposure"
        "engage or maintain nuisance",
        "{charged_with} making harassing phone calls to a member of the public",
        "harassing phone calls",
        # Court Edge Case
        "{charged_with} causing a {disturbance} in a court of law",
        "{harassing} a judge or jury member",
        "{charged_with} disrupting court proceedings",
        # Street Gang
        "{charged_with} participating in a street gang",
        "{improper} gang activity",
        "{charged_with} engaging in organized criminal activity",
        # Noisiness
        "{charged_with} shouting too loudly by the {place}",
        "playing loud music by a {place}",
        "{improper} sound reproduction",
        # Domestic Assault Edge Case
        "{charged_with} having a loud domestic argument",
        "domestic argument {without} violence",
    ],
    "Breaking Urban Rules": [
        # Breaking urban rules
        "{failure to} to pay public transportation fare"
        "{failure to} pay fare on the bus",
        "attempted to evade paying transit fare",
        "{charged_with} pedestrian violation",
        "{improper} obstruction of a passageway",
        "{charged_with} jaywalking",
        "{charged_with} crossing by a {place} where there is no crosswalk",
        "{charged_with} littering in a public {place}",
        "littering by a {place}",
        "{severe} littering",
        "{charged_with} littering, first degree",
        "urinating or defecating by a {place}",
        "{charged_with} {improper} littering",
        "{charged_with} {improper} dumping of waste",
        "{improper} dumping",
        "{charged_with} {improper} curfew violation at night",
        "{charged_with} a misdemeanor, interfering with public transportation",
        "{charged_with} placement of temporary signs at a {place} without obtaining the required permits",
        "no person shall be in park after designated hours",
        # Pets
        "{charged_with} leaving dog at large",
        "{charged_with} not controlling dog by the {place}",
        "{charged_with} running at large",
        "{improper} control of dog",
        "{failure to} have a vaccination certificate for a pet",
    ],
    "Public Intoxication": [
        # Alcohol-related offenses
        "{charged_with} public intoxication",
        "being publicly {under_the_influence} at the {place}",
        "{under_the_influence} of alcohol whilst not driving",
        "an {alcoholic_beverage} was found in the {motor_vehicle}",
        "an {alcoholic_beverage} is in the {motor_vehicle} but is not the driver's",
        "passenger in a {motor_vehicle} with an open container",
        "{charged_with} {improper} possession of an {alcoholic_beverage}",
        "{improper} possession of an {alcoholic_beverage}",
        "{alcoholic_beverage}",
        "{possessing} an {alcoholic_beverage}, misdemeanor",
        "{possessing} a {alcoholic_beverage} which was not closed",
        "{possessing} a {alcoholic_beverage} in a {improper} place",
        "consuming alcohol in a public {place}",
        "{improper} {possessing} of alcohol",
        "{improper} consumption of alcohol by a person who is not a {minor}",
        # Drug edge cases
        "{under_the_influence} by a non-drug substance",
        "{under_the_influence} of a substance that is not a drug",
        # Drug Trafficking Edge Cases
        "{charged_with} transporting {alcoholic_beverage}",
        "{possessing} an {alcoholic_beverage} with intent to {distribute}",
    ],
    "Rioting": [
        "rioting",
        "looting",
        "unlawful assembly to riot",
        "unlawful protest to riot",
        "conspiracy to riot",
        "intending to riot",
        "planning to riot",
        "burning down shops during a riot",
        "attempted to incite a riot among bystanders",
        "hurling projectiles at law enforcement in a riot",
        "{improper} mob action",
        "mobbing {officer} at a {place}",
    ],
    "Underage Offense": [
        # Alcohol
        "{minor} possession of alcohol",
        "{minor} in possession of an {alcoholic_beverage}",
        "consumption of alcohol under the age limit",
        "{minor} using alcohol",
        "{minor} {under_the_influence}",
        "{minor} {possessing} alcohol",
        "found a {minor} {possessing} a {alcoholic_beverage}",
        "underage drinking",
        "{minor} purchasing alcohol, misdemeanor",
        "{minor} found drinking near a {place}",
        "{minor} caught with open containers of alcohol",
        "cited for underage {possessing} of a {alcoholic_beverage} at {place}",
        "found {minor} consuming alcohol near {place}",
        "{minor} discovered heavily intoxicated at {place}",
        "{minor} still {under_the_influence} after leaving a party",
        "police found a {minor} with beer behind a {place}",
        "accused a {minor} of underage {possessing} of alcoholic drinks",
        "{minor} attempted to purchase alcohol at a local store",
        "arrested {minor} for underage drinking near {place}",
        "found {minor} intoxicated near the {place} with {alcoholic_beverage}",
        "caught a {minor} carrying multiple bottles of alcohol in a backpack",
        # Tobacco
        "{minor} possession of tobacco",
        "{minor} {possessing} tobacco",
        "{minor} smoking cigarettes",
        "possession of tobacco by a {minor}",
        "{charged_with} underage tobacco possession",
        "{possessing} a {alcoholic_beverage} while underage 21",
        "{improper} transaction with a {minor} {minor_degree_level}",
        "{charged_with} providing tobacco to a {minor}",
    ],
    "Public Institution Violation": [
        # Prison Violation
        "{charged_with} introducing contraband into a {prison}",
        "{possessing} contraband in a {prison}",
        "{possessing} a prohibited objects in a {prison}",
        "entry into {prison} with {improper} contraband",
        "intending to {distribute} {improper} items in a {prison}",
        "{prison} resident smuggled {improper} items",
        "{charged_with} {possessing} of {improper} items in a {prison}",
        "keeping a {improper} phone while residing at a {prison}",
        "{possessing} contraband while in a {prison}",
        "attempted to bring {improper} items into a {prison}",
        "caught with {improper} items inside a {prison}",
        "attempted to introduce {improper} items into a {prison}",
        "caught with {improper} items inside a {prison}",
        "smuggling {improper} items into a {prison}",
        "smuggling contraband into a {prison}",
        "{conspiracy_to} introduce contraband into a {prison}",
        "{conspiracy_to} smuggle {improper} items into a {prison}",
        "{improper} distribution of items in a {prison} which are not drugs",
        "selling {improper} contraband in a {prison} but not {drug}",
        "{conspiracy_to} convey {improper} items in a {prison} that are not drugs",
        "{conspiracy_to} provide {improper} object to an inmate - felony"
        "{charged_with} contraband introduction {minor_degree_level}",
        "{charged_with} bringing {improper} items into a {prison}, misdemeanor",
        "inmate {possessing} tobacco, electronics or a phone",
        # Communication Device Violation
        "{charged_with} tampering with a communication device in a {prison}",
        "{improper} use of a communication device in a {prison}",
        "{charged_with} damaging or interrupting a communication device",
    ],
    "Illicit Business": [
        # General criminal activity
        "{conspiracy_to} commit racketeering",
        # Gambling
        "{charged_with} illegal gambling near a {place}",
        "engaged in gambling at the {place}",
        "{improper} gambling",
        "gambling",
        "{improper} wagering while playing cards at {place}",
        "{charged_with} {improper} betting",
        "{charged_with} operating an {improper} gambling den",
        "participating in high-stakes betting {without} permission",
        "involved in an underground gambling ring {without} required permits",
        "detained for organizing illicit gambling events at {place}",
        "suspected of running {improper} gambling activities in {place}",
        "arrested for engaging in covert gambling operations",
        "{improper} betting schemes at {place}",
        "operating a secret gambling network in {place}",
        "implicated in {improper} high-roller gambling events at {place}",
        "witnessed at a clandestine gambling club in {place}",
        # Unlicensed transit
        "{charged_with} {improper} soliciting of ride share services",
        "{charged_with} {improper} solicitation of rides",
        "{improper} solicitation",
        "{improper} selling of services with {invalid} license",
        "contracting with an {invalid} license",
        "{charged_with} contracting without a license",
        # Prostitution
        "prostitution",
        "{charged_with} soliciting prostitution",
        "{charged_with} loitering and solicitation of sex acts",
        "{conspiracy_to} offer sex acts",
        "{improper} pimping",
        "{charged_with} operating a prostitution business",
        "{charged_with} operating a {improper} brothel"
        "{conspiracy_to} sell immoral services",
        "{charged_with} selling alcohol without a license",
        "{conspiracy_to} start an {improper} alcohol distribution business",
    ],
    "Non-Drug Illicit Items": [
        "{possessing} child pornography",
        "{charged_with} {possessing} child pornography",
        "{charged_with} {possessing} child pornography on their hard drive",
        "{possessing} a computer with {improper} images of children",
        "{possessing} pornographic material of a {minor}",
        "{possessing} pornographic images of a {minor}",
        "found {possessing} pornographic images of children",
        "{possessing} explicit images of a {minor}",
        "{charged_with} {possessing} indecent images of a {minor}",
        "{conspiracy_to} {distribute} child pornography",
        "{possessing} a sexual performance by a child",
        "{possessing} a pornographic video of a {minor}",
    ],
    "Ambiguous Offense": [
        "{conspiracy_to} commit an offense",
        "{charged_with} committing an unspecified offense",
        "{conspiracy_to} do something {improper}",
        "{conspiracy_to} do a crime",
        "{charged_with} criminal activity",
        "offenses involving {victim}",
        "unspecified offenses involving a {minor}",
        "offenses involving a {family_member}",
        "offenses at a {place}",
        "regular violator",
        "{charged_with} an unknown offense",
        "criminal simulation",
        "charge not specified",
        "{reckless} offenses",
        "{improper} offense",
        "{improper} repeat offender",
        "{improper} habitual offender",
        "{improper} habitual violator",
        "{improper} repeat violator",
        "conspiracy",
        "{minor_degree_level}",
        "unknown",
        "{charged_with} an unspecified crime",
        "{charged_with} an ambiguous offense",
        "{charged_with} ordinance violation",
        "{charged_with} violating local ordinance",
        "{charged_with} truancy",
    ],
    "Recreational Violation": [
        "{charged_with} fishing without a permit",
        "fish without a permit",
        "{charged_with} hunting without a license",
        "{improper} recreational fishing",
        "{improper} recreational hunting",
        "{possessing} wood that was unlawfully chopped down",
        "{improper} trafficking of wildlife",
        "{charged_with} {improper} possession of wildlife",
        "{charged_with} {improper} hunting of protected species",
        "{charged_with} {improper} fishing in a protected area",
        "{charged_with} poaching",
        "{charged_with} {improper} trapping of animals",
        "{charged_with} {improper} collection of plants",
        "{charged_with} {improper} collection of wildlife",
        "{charged_with} cruelty to animals",
    ],
    "Murder": [
        "intentionally killed another person",
        "committed premeditated murder",
        "murdered someone in cold blood",
        "murder",
        "{charged_with} murder, a {severe} felony",
        "{conspiracy_to} commit murder",
        "premeditated killing",
        "planned killing",
        "murdered {victim}",
        "killed {victim} intentionally",
        "took a life with clear intent at {place}",
        "fatally shot a {victim} with malicious forethought",
        "{charged_with} homicide with prior planning",
        "deliberately ended someone's life at {place}",
        "charged with orchestrating a murder",
        "assassinated a {victim} in a targeted attack",
        "executed a deadly plan against {victim}",
        "plotting and carrying out a homicide",
        "committing a planned homicide on {victim}",
        "accused of intentionally slaying a {victim}",
        "killing a {victim} in a premeditated manner",
        "{charged_with} deliberate homicide at the {place}",
    ],
    "Non-Negligent Manslaughter": [
        "killed {victim} in the heat of the moment",
        "{charged_with} intentionally caused someone’s death during a fight",
        "killed another person in a non-accidental situation",
        "manslaughter",
        "{charged_with} planned manslaughter, a {severe} felony",
        "shot someone to death intentionally",
        "intentional manslaughter",
        "fatally injured a {victim} in a spontaneous altercation",
        "death resulted from a sudden conflict with {victim}",
        "emotional outburst leading to the fatality of {victim}",
        "non-accidental homicide classified under manslaughter",
        "a fatal encounter with no prior intent but still purposeful",
        "a violent confrontation leading to {victim}'s death",
        "killed a {victim} amid intense provocation",
        "admitted to causing fatal harm without preplanning",
        "ended the life of a {victim} in a volatile dispute",
        "manslaughter charges for an impulsive killing",
        "unplanned but intentional act causing death",
        "{charged_with} lethally harmed {victim} during a {fight}",
        "offense of killing someone in an emotional rage",
        "accused of manslaughter for a sudden deadly action"
    ],
    "Vehicular Manslaughter": [
        "caused a fatal accident while driving recklessly",
        "killed a pedestrian in a car accident",
        "killed someone through careless driving",
        "hit someone while driving, resulting in death",
        "killed passerby whilst driving",
        "fatally struck a {victim} with a {motor_vehicle}",
        "charged with driving irresponsibly leading to a death",
        "caused a deadly crash at a {place}",
        "took someone's life in a high-speed collision",
        "ran over a {victim} due to {reckless} driving",
        "failed to stop, causing a fatal vehicle accident",
        "{charged_with} negligent operation of a {motor_vehicle} leading to death",
        "killed {victim} in a drunk driving incident",
        "lost control of {motor_vehicle}, causing a fatality",
        "death occurred after colliding with a {victim} on the road",
        "charged with vehicular homicide following an accident",
        "unintentional killing with a {motor_vehicle}",
        "struck a {victim} in a crosswalk causing fatal injuries",
        "indicted for vehicular manslaughter in a {place}",
        "accidentally ended {victim}'s life with reckless operation"
    ],
    "Negligent Manslaughter": [
        "caused death by failing to follow safety precautions",
        "accidentally killed another person by negligence",
        "{charged_with} caused death through negligence",
        "accidentally caused death",
        "death occurred because of {reckless} oversight",
        "lacked due caution leading to fatal incident",
        "{failure to} maintain safe conditions caused a death",
        "unintentionally ended a life by ignoring rules",
        "led to a deadly outcome through carelessness",
        "accidentally caused someone's demise due to lack of attention",
        "a fatal slip-up caused by negligence",
        "bypassed safety measures resulting in a death",
        "forgot essential precautions leading to someone's death",
        "negligently handled equipment causing fatality",
        "responsible for a death due to omission of care",
        "accidentally ended the life of {victim} through incompetent actions",
        "unintentional killing tied to disregard for safety",
        "{charged_with} failing to prevent hazards resulted in a death",
        "did not foresee obvious risks leading to fatality",
        "neglected standard safety protocols, causing fatal outcome"
    ],
    "Kidnapping": [
        "false imprisonment of a {victim}",
        "false imprisonment of a {family_member}, felony",
        "false imprisonment of a {minor}",
        "{severe} kidnap",
        "{improper} imprisonment",
        "{improper} confinement",
        "{improper} abduction",
        "{charged_with} abducting a {victim} against their will",
        "held someone hostage for ransom",
        "{charged_with} abduction",
        "{charged_with} kidnapping",
        "abducting an individual",
        "{charged_with} kidnapping and hiding a person",
        "kidnap of a person",
        "abducting an individual",
        "unlawful confinement of a {victim} in a secret location",
        "forcing a {victim} into a {motor_vehicle} against their will",
        "abducting a {victim} using a {motor_vehicle}",
        "seizing control of someone's movements without permission",
        "detaining a {victim}",
        "taking a {victim} under threat from the {place}",
        "coercing {victim} into captivity",
        "snatching a {victim} from public space",
        "detaining a {victim} for illegal reasons",
    ],
    "Child Abuse": [
        "child abuse",
        "{charged_with} physically harming a child",
        "{inflicted} {severe} harm to a child",
        "neglected a child’s well-being causing harm",
        "abused a {minor} mentally and physically",
        "{inflicted} {severe} child abuse",
        "{strangled} a child",
        "shown {negligence} towards a {minor}",
        "{charged_with} {reckless} child endangerment",
        "{charged_with} repeatedly abusing a child",
        "{improper} neglect of a child, felony",
        "having abused a child at home",
        "{severe} abuse of a child",
        "causing {severe} harm to a child",
        "abused a child physically but not sexually",
        "{charged_with} physically harming a child but not sexually",
        "{charged_with} neglect of a dependent",
        "{charged_with} cruelty to children"
        "{charged_with} injury to a child",
        # Assault edge case
        "{charged_with} {assault} of a child",
        "{severe} {assault} with injury to a child",
    ],
    "Forcible Sex Offense": [
        "rape in the first degree",
        "first degree rape",
        "{charged_with} criminal sexual conduct",
        "rape in the {minor_degree_level}",
        "{raped} an individual by force",
        "sexual assault of a person using violence",
        "forcibly {raped} another adult at the {place}",
        "{raped} {victim} against their will",
        "{raped} {victim} at {place}",
        "forced someone into non-consensual sexual activity",
        "{raped} another adult by force",
        "{charged_with} sexual violence",
        "{charged_with} rape",
        "{charged_with} rape at a {place}",
        "{severe} sexual assault",
        "{charged_with} rape of adult",
        "{charged_with} intention to assault sexually",
        "intent to sexually assault",
        "forcible sex offense",
        "{charged_with} sexual battery",
        "{charged_with} forcible sex offense at {place}",
        "{conspiracy_to} commit rape",
        "{charged_with} sodomy, {minor_degree_level}",
        # Sex with a minor
        "rape of a {minor}",
        "engaged in sexual relations with a {minor}",
        "communication with a {minor} for immoral purposes",
        "texting a {minor} for immoral reasons",
        "having sent texts to a {minor} for sexual reasons",
        "{charged_with} having communicated with a {minor} with improper intentions",
        "indecency with a {minor}, felony",
        "lewd acts upon a {minor}",
        "carnal knowledge of a {minor}",
        "indecent liberties with a {minor}",
        "{charged_with} enticing a {minor}"
        # Edge case
        "{charged_with} lewd or lascivious  conduct, felony "
        "{charged_with} offensive touching",
        "{charged_with} trafficking for sexual servitude - felony",
    ],
    "Aggravated Assault": [
        "aggravated assault",
        "{severe} assault",
        "{charged_with} {severe} {assault}",
        "{charged_with} {severe} domestic assault",
        # First Degree
        "{assault} in the first degree",
        "first degree {assault}",
        "{charged_with} {assault} in the 1st degree",
        # Bodily Injury
        "{severe} assault {inflicted} {light} bodily harm",
        "{assault} which {inflicted} minor injuries",
        "{charged_with} assault causing bodily injury",
        "{charged_with} aggravated assault",
        "{assault} with {reckless} intent to injure {victim}",
        "{severe} domestic {assault} with bodily injury",
        "domestic {assault} causing injuries to body",
        "{assault} on {family_member} causing injuries",
        "{severe} beating of an individual resulting in broken bones",
        "{charged_with} {inflicted} {severe} injury leading to long-term damage",
        "{assault} causing bodily injury requiring emergency treatment",
        "assault {inflicted} {severe} harm and {severe} injuries",
        "{assault} resulted in severe bodily trauma needing intensive care unit treatment"
        "{inflicted} {severe} injury requiring hospitalization",
        "{minor_degree_level} {assault} causing bodily injury",
        "{assault} in the {minor_degree_level} still {inflicted} minor injury",
        "{severe} malicious wounding",
        # using a weapon
        "{severe} {assault} involving a {weapon}",
        "{assault} with a {firearm}",
        "used a {weapon} to seriously wound a person",
        "{severe} aggravated {assault} using a {weapon}",
        "{severe} aggravated {assault} using a {firearm}",
        "{charged_with} {assault} with a deadly {weapon} at {place}"
        "{minor_degree_level} {assault} using a {weapon}",
        "batter by use of a {weapon}",
        # Choking
        "{strangled} with a {weapon} causing severe injury",
        "{strangled} {victim} with a rope causing {severe} injuries",
        "{strangled} {victim} causing {severe} injury requiring surgery",
        "{strangled} {family_member} in a violent domestic altercation",
        "{strangled} a {victim} until they nearly lost consciousness",
        "severely {strangled} someone during a {fight}",
        "{strangled} an individual requiring medical attention",
        "{charged_with} strangulation and suffocation",
        # Felonious Assault
        "felonious {assault}",
        "felon {charged_with} {assault}",
        "{assault} - felony and not misdemeanor",
        "{assault} {minor_degree_level} felony",
        "{assault} in the first degree, felony",
        # Child abuse edge case
        "{assault} with injuries but not on a child",
        "{severe} assault on a {family_member} but not a minor",
    ],
    "Simple Assault": [
        "{charged_with} {assault}",
        "simple {assault}",
        "{assault}",
        "{charged_with} {assault} as a misdemeanor",
        "{charged_with} {assault} that was not {severe}"
        "{assault} {without} bodily harm",
        "{charged_with} domestic abuse",
        "{assault} on {family_member}",
        "domestic {assault} with physical contact",
        "domestic {assault}",
        "{charged_with} domestic violence",
        "{assault} in the {minor_degree_level}",
        "{minor_degree_level} {assault}",
        "{charged_with} {minor_degree_level} {assault}",
        "{assault} in the {minor_degree_level} but not the first degree",
        "{charged_with} simple {assault}",
        "{charged_with} domestic {assault}",
        "{charged_with} minor {assault}",
        "{assault} on a {officer}",
        "resisting an {officer} with violence",
        "violently resisted arrest by an {officer}",
        "{hit} an officer who was arresting them",
        "{charged_with} having {hit} a {officer} during arrest",
        "{assault} - {minor_degree_level}",
        "{charged_with} {assault} in the {minor_degree_level}",
        # No injuries
        "domestic {assault} {without} injury caused",
        "{charged_with} {assault} {without} bodily injury",
        "{assault} on a {family_member} {without} body injury",
        "{assault} {without} causing injuries",
        "{hit} someone in a {light} {fight} but caused no serious harm",
        "{charged_with} {assault} which {inflicted} no injuries",
        "got into a {fight} and shoved a person causing no injuries",
        "{charged_with} simple {assault} after pushing {victim} at {place}",
        # No weapon
        "{assault} with no {firearm}",
        "{charged_with} {assault} without a {weapon}",
        "{assault} {without} a {weapon}",
        # No felony
        "{charged_with} non felonious {assault}",
        "{assault} but not felony",
        "{assault} - misdemeanor and not felony",
        "{charged_with} domestic battering on a {family_member}",
        # Public Order Edge Case
        "{charged_with} a violent domestic argument causing injury",
        "assault and resist a {officer}",
        # No Child
        "{assault} but not on a {minor}",
    ],
    "Weapons Offense": [
        "{possessing} {weapon}",
        "{possessing} a firearm {without} a permit",
        "possessed a {weapon} illegally",
        "{improper} possession of a regulated {firearm}",
        "recklessly wielding a {weapon} - felony",
        "regulated {weapon} illegal possession",
        "{improper} possession of a regulated {weapon}",
        "{charged_with} {possessing} a {weapon}",
        "{possessing} a {firearm} with an {invalid} license",
        "{charged_with} unregistered {firearm}",
        "{possessing} a {firearm} without a license",
        "possession of {weapon} {without} authorization",
        "felon in possession of a weapon",
        "{possessing} a {weapon} as a convicted felon",
        "violent felon {possessing} a {weapon}",
        "wearing and carrying an unconcealed {weapon}",
        "{improper} storage of a {firearm}",
        "{charged_with} weapons offense",
        "{improper} use of a {weapon}",
        "possession of firearm during commission",
        "{charged_with} not properly storing a {weapon}",
        "{possessing} an {invalid} weapons license",
        "{charged_with} {possessing} a {firearm} {without} a valid permit",
        "{charged_with} possession of a {weapon} without required registration",
        "{charged_with} unlawful carrying of a concealed {firearm}",
        "illegal possession of a {weapon} by a prohibited person",
        "{charged_with} having an unlicensed firearm in a public space",
        "felon found in possession of a restricted {weapon}",
        "{charged_with} carrying a {weapon} in a prohibited area",
        "{charged_with} improper storage of a {weapon}, violating safety laws",
        "attempted to purchase a {firearm} illegally",
        "{charged_with} possession of high-capacity magazines in violation of the law",
        "{charged_with} failure to report a lost or stolen {weapon}",
        "{charged_with} unlawful sale of ammunition"
        "{charged_with} {improper} sale of ammunition",
        "{improper} weapons trafficking",
        "{conspiracy_to} commit misconduct with weapons",
        "{conspiracy_to} help a convicted criminal obtain a {firearm}",
        "{improper} possession of a {firearm} by a violent felon",
        "brandished a {weapon} at a {place}",
        # Drug Trafficking edge case
        "{possessing} a {firearm} while committing a {drug} trafficking crime",
        "{conspiracy_to} {distribute} firearms illegally",
    ],
    "Robbery": [
        "{severe} robbery",
        "{charged_with} robbery - felony",
        "{charged_with} robbery",
        "armed carjacking",
        "held up a store at gunpoint demanding money",
        "took {stolen_property} at gunpoint from a cashier",
        "seized {stolen_property} with a knife during a robbery",
        "brandished a {weapon} while demanding valuables",
        "used a firearm to threaten a {victim} into handing over {stolen_property}",
        "pointed a gun at a {victim} and demanded their wallet",
        "threatened a {victim} with a {weapon} while demanding money",
        "committed a violent mugging stealing {stolen_property} from a passerby",
        "robbed a bank teller while wielding a {weapon}",
        "stole {stolen_property} from a store clerk under threat of force",
        "forcibly took {stolen_property} from a {victim} at {place}",
        "used physical violence to rob {stolen_property} from a person",
        "robbed a convenience store by threatening the cashier",
        "carjacked a {motor_vehicle} at gunpoint from its owner",
        "assaulted and robbed a pedestrian near {place}",
        "threatened to harm a bank employee unless they handed over cash",
        "{charged_with} armed robbery after brandishing a gun at a store",
        "{charged_with} attempted robbery for trying to snatch a purse at knifepoint",
        "attempted to rob a jewelry store but was stopped by security",
        "{charged_with} conspiracy to commit robbery at a bank",
        "{charged_with} committing aggravated robbery at {place}",
        "{charged_with} attempting to rob a gas station clerk",
        "{charged_with} home invasion robbery",
        "{charged_with} armed home invasion",
    ],
    "Hit and Run with Bodily Injury": [
        "{charged_with} hit and run causing {severe} injuries",
        "hit and run {without} property damage but with bodily injury",
        "hit {victim} with a car and fled the scene",
        "caused an accident and left the {victim} injured without providing help",
        "drove away after hitting a {victim} on a crosswalk",
        "ran from scene after causing injury",
        "left the scene of a {motor_vehicle} crash which left bodily injuries",
        "left the scene of an accident which caused {severe} injuries",
        "{charged_with} leaving the scene of an accident with that led to injuries",
        "fled after hitting a {victim} with a {motor_vehicle}, {severe} injuries",
        "attacked {victim} and ran away",
        "escaped after injuring person",
        "causing injury to {victim} and fleeing",
        "failed to stop after striking a cyclist, leaving them hurt",
        "fled the scene following a collision causing bodily harm",
        "recklessly hit {victim} with {motor_vehicle} then evaded authorities",
        "indicted for hit-and-run leading to injuries",
        "{charged_with} knocked over a pedestrian and drove off",
        "driver left the scene after an injurious crash",
        "struck a {victim} crossing the street and failed to remain",
        "skipped out on the accident scene leaving injuries behind",
        "absconded immediately after harming a {victim}",
        "hit {victim} near {place} and didn't stop",
        "recklessly caused harm in an accident before fleeing the site"
    ],
    "Other Violent Offense": [
        "{reckless} endangerment",
        "{reckless} endangerment but not while driving",
        "{charged_with} endangering other people",
        "{charged_with} {reckless} endangerment",
        "{improper} causing of danger",
        "{charged_with} dangerous conduct",
        "{charged_with} deadly conduct",
        "posing a {severe} risk to safety",
        "wanton endangerment",
        "{charged_with} dangerously throwing a missile",
        "throwing a projectile at a {motor_vehicle}",
        "{severe} throwing of objects",
        "launching a missile at a {motor_vehicle}",
        "hurling a rock at a {place}",
        "{charged_with} {reckless} discharging of a {firearm}",
        "{charged_with} discharging a {firearm} in a busy area",
        "discharged a {firearm} in a public area",
        "{charged_with} {reckless} endangerment with a {firearm}",
        "{charged_with} discharging a {firearm} but no injuries",
        "shooting a {firearm} but not hitting anyone",
        "causing unnecessary danger to others at a {place}",
        "{charged_with} throwing an object at a train",
        "{severe} terrorism",
        "{charged_with} street terrorism"
        "criminal {disturbance} that endangers the public",
    ],
    "Arson": [
        "set fire to a building intentionally",
        "burned down a property as an act of vandalism",
        "caused a fire to destroy someone’s belongings",
        "arson",
        "ignited a structure at {place} with malicious intent",
        "started a blaze in a {place} for destructive purposes",
        "{charged_with} deliberately lighting a fire damaging public property",
        "attempted arson by pouring flammable liquid around a house",
        "used an accelerant to spark a blaze at {place}",
        "arrested for trying to burn {victim}'s possessions",
        "torched a vehicle to cause damage",
        "committed arson on a vacant building",
        "suspected of intentionally setting flames in {place}",
        "created a controlled burn that spread unlawfully",
        "plotted to destroy property through fire at {place}",
        "firebombed a garage in a revenge attack",
        "accused of reckless burning endangering the community",
        "setting multiple fires in a spree of arson",
        "attempted to torch a business for insurance fraud",
        "caused extensive fire damage to a {place}"
    ],
    "Fraud": [
        # General fraud
        "defrauded a {victim} out of money through false promises",
        "fraud",
        "{conspiracy_to} commit fraud",
        "defrauded a {victim}",
        "{charged_with} retail fraud",
        "{charged_with} falsification",
        "{charged_with} mail fraud",
        "{charged_with} fraudulent use of a telephone",
        "falsify business records",
        "{charged_with} money laundering",
        "{charged_with} {severe} money laundry",
        "{charged_with} fraudulently obtaining food or lodging",
        # Using a stolen card
        "{charged_with} fraudulent use of a {payment_card}",
        "{improper} use of {payment_card} under $1,500",
        "operated a {payment_card} scam at {place}",
        "fraudulently used a stolen {payment_card} to make a purchase",
        "{charged_with} unauthorized use of a stolen {payment_card} to purchase goods worth ${numeric_quantity}",
        "{charged_with} {payment_card} abuse",
        # Forgery
        "used {fraudulent} currency at {place}",
        "submitted {fraudulent} tax returns",
        "{possessing} {fraudulent} instruments",
        "{possessing} {fraudulent} bank bills",
        "{improper} forgery of documents",
        "fabricated {improper} documents to deceive {victim}",
        "falsifying paperwork to purchase a {weapon}",
        "false statements in application for a {firearm}",
        "falsifying paperwork to purchase a {motor_vehicle}",
        "{charged_with} knowingly giving {fraudulent} information for {financial_gain}",
        "{possessing} {fraudulent} documents to purchase a {weapon}",
        "{charged_with} making {fraudulent} statement to purchase a firearm",
        "{charged_with} falsifying statement to purchase {motor_vehicle} insurance",
        "{improper} making of a {fraudulent} financial statement",
        "{charged_with} committing financial fraud by falsifying documents",
        "{charged_with} uttering and publishing",
        "uttering a false statement and published forged documents",
        "{charged_with} uttering a false writing",
        "{charged_with} forging a public record, felony",
        "false application for driver's license or {identification}",
        # Traffic Edge cases
        "showed a {fraudulent} driver's license to a {officer}",
        "driving with a {fraudulent} license",
        "driving with {fraudulent} insurance",
        "{charged_with} insurance fraud",
        # Conversion
        "{charged_with} criminal conversion of {stolen_property}",
        "{improper} conversion of {stolen_property}",
        "{charged_with} selling unlawfully obtained {stolen_property}",
        # Check Fraud
        "{charged_with} theft by check of a {victim}",
        "{charged_with} passing a bad check",
        "{charged_with} using a {fraudulent} check",
        "{improper} theft of check",
        "{charged_with} theft of check of a {victim}",
        "{charged_with} using checks with insufficient funds",
        # Theft by deception
        "{charged_with} theft by {deception}",
        "theft with {deception}",
        "stealing from a {victim} by deceiving them",
        "{charged_with} theft using deceptive means",
        "{charged_with} giving false information to obtain a refund",
        "{failure to} work after being paid",
        # Not paying tax
        "{failure to} file income tax",
        "{improper} income tax violation",
        "{failure to} pay taxes due to state",
    ],
    "Identity Theft": [
        # Identity Theft
        "engaged in {severe} identity theft for {financial_gain}",
        "{charged_with} {improper} theft of {identification}",
        "{severe} {identification} theft",
        "{charged_with} using another person's {identification} for criminal purposes",
        "{improper} use of another person's {identification}",
        "{improper} use of a {victim}'s {identification}",
        "{improper} use of false {identification}",
        "falsely use name and date of birth of another",
        "using false {identification} for the purpose of fraud",
        "assisting in obtaining another person's {identification} illegally",
        "use of another person's {identification} without permission",
        "{charged_with} stealing of {identification} for {improper} purpose",
        "fraudulent use of someone else's {identification}",
        "{possessing} stolen {identification} that is not their own",
        "{possessing} {identification} to commit forgery",
        "{conspiracy_to} impersonate another",
        "{improper} impersonation",
        "impersonating a {victim}, misdemeanor",
        "{charged_with} false personation",
        "{charged_with} unauthorized utilization of a stolen access device to get goods worth ${numeric_quantity}",
        "{charged_with} use of access account information without consent",
        "giving false information with intent to be another actual person, misdemeanor",
        "misuse of {identification}"
    ],
    "Embezzlement": [
        "{charged_with} embezzlement",
        "{improper} embezzlement",
        "{charged_with} {improper} use of funds trusted to them",
        "{charged_with} misappropriation of funds",
        "misappropriated company resources for personal use",
        "embezzled money from a non-profit organization",
        "embezzled funds",
        "embezzlement",
        "converted employer’s assets for personal benefit",
        "took {victim}'s money entrusted for safekeeping",
        "diverted corporate funds to private accounts",
        "{charged_with} fraudulently using company credit cards for personal expenses",
        "embezzled petty cash from the office",
        "doctoring financial statements to hide misappropriations",
        "skimmed profits from daily sales",
        "exploited position to siphon organizational funds",
        "pocketed charity donations for personal gain",
        "laundered misappropriated funds through shell accounts",
        "failed to deposit client payments into official accounts",
        "abused trust by transferring money to personal account",
        "secretly withdrew money from company funds",
        "alleged to have rerouted finances to personal bank",
        "stole payroll checks from employees under supervision"
    ],
    "Escape/Flight": [
        "escaped from lawful custody",
        "{severe} fleeing and eluding {officer}",
        "{charged_with} fleeing and eluding an {officer}",
        "attempted to flee from police during an arrest",
        "broke free from {prison} or detention",
        "{charged_with} evading arrest or detention",
        "escape/flight",
        "{charged_with} fleeing",
        "{charged_with} eluding",
        "{charged_with} escape or flight",
        "{improper} escape from a {prison}",
        "{improper} fleeing from {officer} while being detained",
        "attempt to run from a {officer}",
        "flight from {officer}",
        "{charged_with} evading an {officer}",
        "ran away from officers",
        "{charged_with} running from {officer}",
        "escaped from a courthouse before sentencing",
        "fled following a traffic stop to avoid arrest",
        "bolted from an {officer} while in handcuffs",
        "ran away from {place} to evade arrest",
        "evaded law enforcement near a busy {place}",
        "attempted to escape while being transported in a police van",
        "slipped out of custody during a {fight} at the station",
        "endangering others while attempting to elude an {officer}",
        # Traffic Edge cases
        "{charged_with} eluding by speeding over the limit",
        "elude arrest with {motor_vehicle}, misdemeanor",
        "operating a {motor_vehicle} to evade arrest",
        "{improper} vehicular eluding",
        # Obstructing Justice Edge cases
        "{failure to} stop {motor_vehicle} for an {officer}",
        "{failure to} stop driving at command of law enforcement",
        "{failure to} to stop when {officer} signals",
        "stop required on signal of {officer}",
        # Edge case
        "{charged_with} evading arrest with endangerment",
        "fugitive from justice",
    ],
    "Resisting Arrest": [
        "{resisting} arrest",
        "{resisting} arrest by police",
        "{light} {resisting} arrest by an {officer}",
        "resist arrest",
        "{resisting} an {officer} {without} violence, misdemeanor",
        "obstructing being put under arrest by a {officer}",
        "{charged_with} {resisting} law enforcement - felony",
        "{resisting} arrest by an {officer} - felony",
        "{resisting} apprehension",
        "{resisting}, evading or obstructing an {officer}",
        "{resisting} a {officer}",
        "{resisting} {officer}",
        "having resisted arrest",
        "{resisting} being placed in custody",
        "{charged_with} {resisting} being placed in custody by a {officer}",
        "{charged_with} having resisted arrest",
        "resisted capture at {place} following arrest",
        # Assault edge cases
        "{charged_with} having resisted arrest with no violence",
        "{resisting} apprehension by an {officer} without resort to violence",
        "{resisting} arrest but no violence",
        "resist an {officer} {without} {assault}",
        # Taking officer's equipment
        "taking a communication device from an {officer}",
        "attempting to remove a device from an {officer}",
        "{improper} use of {officer} radio",
        # Traffic Edge cases
        "{resisting} arrest or search of owner's {motor_vehicle}",
    ],
    "Obstructing Justice": [
        # Identification
        "{failure to} identify to an {officer}",
        "{charged_with} giving false {identification} to an {officer}",
        "gave false {identification} to an {officer}",
        "gave false {identification}",
        "{charged_with} giving false information",
        "{failure to} give {identification}",
        "falsified their own {identification} to an {officer}",
        "{charged_with} inventing their own {identification} to an {officer}",
        "fugitive failed to identify to an {officer}",
        "{failure to} id fugitive",
        "{failure to} give correct {identification}",
        "{improper} use of a false name",
        "{improper} use of a false name or identification",
        "{charged_with} false reporting",
        "{failure to} give correct {identification}, no intent to impersonate another",
        "gave false {identification} without seeking {financial_gain}",
        "{charged_with} {failure to} identify fugitive",
        "{failure to} give true name to an {officer}",
        "{charged_with} misrepresenting identity",
        "{charged_with} concealing identity",
        "false {identification} to law enforcement",
        "false {identification} to court",
        "provide false {identification} information",
        # False Information
        "{charged_with} giving false information to an {officer}",
        "intentionally lied to an {officer} during an investigation",
        "{charged_with} making a false statement",
        "{improper} giving of fictitious information to an {officer}, misdemeanor",
        "{charged_with} giving a false crime report",
        "making a false report of a violation of the criminal code",
        # Fraud Edge Cases
        "{charged_with} making a false statement with no financial purpose",
        "{charged_with} making a false statement for no particular purpose",
        # Court violation Edge case
        "{charged_with} giving false information in court",
        "{failure to} comply with order from an {officer}",
        # Tampering with evidence
        "{improper} tampering with evidence at the {place}",
        "{charged_with} tampering with official records",
        "destroyed evidence",
        # Making life difficult for officers
        "{charged_with} obstruction of justice",
        "obstruction of justice",
        "{charged_with} obstructing the legal process",
        "{charged_with} destruction of evidence",
        "tampered with evidence while an {officer} was investigating",
        "{failure to} comply with {officer} instructions",
        "attempted {failure to} comply with order or signal of {officer}",
        "{failure to} comply",
        "{failure to} comply with an {officer}'s investigation",
        "{charged_with} interfering with official acts by an {officer}",
        "wasting the time of an {officer}",
        "{charged_with} misusing a 911 call",
        "{charged_with} custodial interference",
        "{charged_with} obstructing official business",
        "{charged_with} hindering judicial proceedings",
        "{charged_with} hindering prosecution of a felony",
        "{charged_with} obstructing administration of law",
        "{charged_with} interfering with an emergency medical technician",
        # Arson Edge cases
        "{charged_with} false fire alarm and calling the police",
        "{charged_with} transmitting a false report of fire",
        # Fraud Edge cases
        "{charged_with} false reporting but not falsification of documents",
    ],
    "Traffic Driving": [
        "speeding near a {place}",
        "operating a {motor_vehicle} in a {improper} manner",
        "driving above the speed limit",
        "driving while {improper}",
        "{charged_with} speeding",
        "{charged_with} driving at {improper} speeds",
        "took part in a race with in the middle of a busy street",
        "drove in speed competition by the {place}",
        "basic speed rule, faster than posted",
        "{charged_with} participating in a speeding contest on the roads by the {place}",
        "{charged_with} vehicle speeding, misdemeanor",
        "speeding in a {motor_vehicle} outside the {place}",
        "{reckless} driving",
        "{reckless} driving that endangers others",
        "{charged_with} {reckless} driving that endangers others",
        "driving in a {reckless} way",
        "{charged_with} {reckless} driving",
        "{reckless} operation of a {motor_vehicle}",
        "{charged_with} following {motor_vehicle} too closely",
        "traffic offense",
        "{charged_with} driving past red light by the {place}",
        "{charged_with} failure to stop at a stop sign",
        "owner of {motor_vehicle} did not signal before turning",
        "failure of driver to signal when turning their {motor_vehicle}",
        "failed to signal",
        "{failure to} signal when turning",
        "{failure to} comply with speed limit at a {place}",
        "{improper} parking",
        "having parked where there are no parking signs by a {place}",
        "parking in a {improper} place",
        "{charged_with} parking violation",
        "{improper} passing of another {motor_vehicle}",
        "{improper} passing of a yellow line",
        "{improper} texting {without} hands free cell phone while driving",
        "{improper} reading of texts without using a hands free cell phone, misdemeanor",
        "unlawful text, send or talk {without} handsfree cell phone",
        "operating a {motor_vehicle} whilst using a cell phone",
        "operators and chauffeurs must have be licensed",
        "{failure to} control a {motor_vehicle}",
        "{motor_vehicle} operator failed to control",
        "{motor_vehicle} nuisance, misdemeanor",
        "{improper} violation of the light law",
        "{failure to} stop at a red light",
        "{charged_with} joyriding",
        "{improper} stopping or parking within 20 feet of a crosswalk",
        "{improper} parking by a sidewalk or driveway",
        "{charged_with} not being parked within 18 inches of curb",
        "{improper} passing",
        "violation of temporary instruction permit",
        "{charged_with} operating an all terrain vehicle on a roadway",
        "{failure to} yield the right of way",
        "{failure to} exercise due caution whilst driving a {motor_vehicle}",
        "{charged_with} driving in excess of 100 mph",
        "{failure to} yield from stop or yield controlled intersection",
        "first degree {reckless} driving",
        "{improper} backing up of a {motor_vehicle}",
        "{charged_with} disregarding official traffic control device",
        "{charged_with} exhibition driving",
    ],
    "Traffic Vehicle": [
        "inoperable license tag light",
        "{improper} tag",
        "license plate light not working on {motor_vehicle}",
        "{failure to} maintain proper {motor_vehicle} operation",
        "{vehicle_part} not functioning",
        "inoperable {vehicle_part} on {motor_vehicle}",
        "{charged_with} defective equipment in {motor_vehicle}",
        "{motor_vehicle} {vehicle_part} was not functioning",
        "defective {vehicle_part}",
        "{failure to} maintain operation of {vehicle_part}",
        "{charged_with} {vehicle_part} violation",
        "{charged_with} using {invalid} plates",
        "{charged_with} display plates of another",
        "{motor_vehicle} license plate light was not switched on",
        "{motor_vehicle}'s rear lights not functioning",
        "{motor_vehicle} lights not working",
        "operating {motor_vehicle} with {improper} {vehicle_part}",
        "{motor_vehicle} lights were not functioning",
        "{failure to} wear seat belt",
        "{failure to} dim {motor_vehicle} lights",
        "seat belt violation",
        "{motor_vehicle} owner was not wearing seat belt",
        "was not wearing a safety belt while operating {motor_vehicle}",
        "booster seat violation",
        "{vehicle_part} violation",
        "{vehicle_part} violation, misdemeanor",
        "all passengers did not have their safety belts on in the {motor_vehicle}",
        "{charged_with} not wearing a seat belt",
        "{charged_with} failing to wear a seat belt while driving",
        "no child restraint in {motor_vehicle}",
        "{motor_vehicle} {vehicle_part} required",
        "{failure to} dim lights",
    ],
    "Traffic Paperwork": [
        "{charged_with} driving under a {invalid} licence",
        "{charged_with} driving under suspension",
        "{charged_with} driving under restraint",
        "driving on {invalid} license and privilege",
        "driving {without} a valid license",
        "authorized to drive owner's {motor_vehicle} but not licensed",
        "driving {without} insurance",
        "{without} insurance",
        "{charged_with} driving while barred",
        "driving while license {invalid} due to having being {under_the_influence}",
        "driving license {invalid} for being {under_the_influence}",
        "barred from operating a {motor_vehicle}",
        "unlicensed operation of a {motor_vehicle}",
        "driving with {invalid} license",
        "insurance {invalid}",
        "insurance that has been revoked",
        "insurance violation",
        "{without} operator's license",
        "driving on a {invalid} license, misdemeanor",
        "no driver's license",
        "{failure to} show license to an {officer}",
        "{failure to} register a {motor_vehicle}",
        "{failure to} notify department of motor vehicles about address change",
        "{failure to} show driver's license or identification",
        "failure of {motor_vehicle} owner to maintain insurance",
        "{without} valid driving licence",
        "{charged_with} operating a {motor_vehicle} without a license",
        "driving a {motor_vehicle} {without} insurance by the {place}",
        "driving while license {invalid} or {invalid}",
        "driving while {invalid}/revoked",
        "{invalid} registration plate on {motor_vehicle}",
        "driving {motor_vehicle} with an {invalid} registration plate",
        "permitted another to drive a {motor_vehicle} with an {invalid} license",
        "{charged_with} allowing an unlicensed {family_member} to operate a {motor_vehicle}",
        "{failure to} show financial responsibility documentation",
        "{charged_with} {failure to} maintain financial responsibility",
        "{failure to} provide financial responsibility of driver",
        "operating a {motor_vehicle} without required financial responsibility",
        "financial responsibility law",
        "{failure to} reinstate a {motor_vehicle} license",
        "drive after forfeit license",
        "operate an uninsured {motor_vehicle}",
        # DUI Edge cases
        "driving under a {invalid} license due to driving {under_the_influence}",
        "driving under a {invalid} license due to failure to appear",
        "{invalid} driver's license, revoked because of {under_the_influence} driving",
        # Fraud Edge Case
        "driving under an {invalid} license but not a {fraudulent} license",
        "driver's insurance is {invalid} but not {fraudulent}",
        "{failure to} purchase a driver's license",
        # Larceny Edge case
        "{charged_with} permitting unauthorized person to drive"
        # Public Order Edge Case
        "{failure to} produce insurance {identification}",
    ],
    "DUI": [
        "driving under the influence of alcohol",
        "driving with a {improper} blood alcohol content and license suspended",
        "{improper} blood alcohol content of {numeric_quantity}%",
        "driving a {motor_vehicle} with a high blood alcohol content",
        "{charged_with} blood alcohol content over the legal limit",
        "{motor_vehicle} operator refused to take a blood alcohol content test",
        "driving while {under_the_influence}",
        "{severe} driving {under_the_influence} - felony",
        "driving while seriously {under_the_influence}",
        "operating a {motor_vehicle} while {under_the_influence}",
        "{charged_with} driving a {motor_vehicle} while {under_the_influence}",
        "driving a {motor_vehicle} while {under_the_influence} near a {place}",
        "drink driving outside a {place}",
        "{charged_with} driving whilst {under_the_influence}",
        "consuming alcohol while operating a {motor_vehicle}",
        "using alcohol while driving a {motor_vehicle}",
        "{charged_with} {possessing} alcohol while driving by a {place}",
        "{under_the_influence} driving",
        "consuming a {drug} while driving by the {place}",
        "impaired while driving a {motor_vehicle}",
        "operation of a {motor_vehicle} while {under_the_influence}",
        "the driver's open container was found in the {motor_vehicle}",
        "{charged_with} operating a {motor_vehicle} with the driver drinking from an open container",
        "{motor_vehicle} operator {possessing} an open container",
        "{motor_vehicle} operator {possessing} an alcoholic container which is not closed",
        "{motor_vehicle} operator {possessing} an alcoholic container which does not belong to the passenger"
        "driving while {under_the_influence} with a {minor} in the {motor_vehicle}",
        "driving while {under_the_influence} with {family_member} in the {motor_vehicle}",
        "driving while {under_the_influence} with a {minor_degree_level} aggravating factor",
        "operating a vehicle {under_the_influence} - refusal",
        "actual physical control of a {motor_vehicle} {under_the_influence}",
        "{charged_with} driving or being in actual physical control with an alcohol concentration",
        "operating {under_the_influence}",
        "{charged_with} driving with measurable controlled substance",
        #Traffic Edge Case
        "operation without being in reasonable control of {motor_vehicle}",
        # Underage edge case
        "driving while {under_the_influence} with a {minor} in the {motor_vehicle}",
        "{charged_with} driving {under_the_influence} with a {minor} as a passenger",
    ],
    "Immigration": [
        "{charged_with} reentry after deportation",
        "{improper} reentry of removed alien",
        "entered the country illegally",
        "violated immigration laws by overstaying a visa",
        "assisted someone in evading immigration authorities",
        "{improper} entry without inspection at the border",
        "{improper} entry into the usa",
        "{improper} entry into the united states",
        "transporting {improper} aliens",
        "{improper} alien",
        "smuggling immigrants",
        "immigration offense",
        "{improper} crossing at border",
        "aided {improper} entry into the usa",
        "evaded border security",
        "{charged_with} evasion of border {officer}"
        "smuggling of migrants",
        "{improper} migration",
        "crossed border without proper documentation",
        "harbored undocumented individuals at a {place}",
        "smuggled migrants across the united states border",
        "arrived at port of entry with an invalid visa",
        "{charged_with} attempting to enter the united states by wilfully concealing facts",
        "{charged_with} concealment of facts about reentry",
        "{conspiracy_to} aid aliens to evade and elude examination",
        "{conspiracy_to} harbour illegal aliens",
        "{conspiracy_to} smuggle illegal immigrants across the border",
        # Edge cases
        "{improper} entry",
        "{improper} reentry",
    ]
}

# Dictionary of possible replacements for placeholders
placeholder_options = {
    "hit": ["slapped", "hit", "punched", "fought", "punching", "scuffled", "shoved", "pushed"],
    "light": ["light", "minor", "negligible", "small", "tiny", "insignificant", "mild"],
    "fight": ["fight", "altercation", "heated argument", "heated exchange", "argument", "scuffle"],
    "inflicted": ["inflicted", "caused", "imposed", "resulted in", "brought about"],
    "family_member": ["spouse", "ex spouse", "family member", "wife", "husband", "girlfriend",
                      "sister", "mother", "cohabitant"],
    "raped": ["raped", "sexually assaulted", "forcing sex on", "assaulting sexually"],
    "strangled": ["choked", "strangled", "suffocated", "put hands around the neck of", "throttled", "strangling",
                  "impeded blood circulation"],
    "severe": ["severe", "aggravated", "serious", "major", "life-threatening", "extreme", "grievous", "corporal"],
    "possessing": ["possessing", "using", "having", "in possession of", "owning", "carrying", "found with"],
    "place": ["school zone", "library", "courthouse", "shopping street", "main street", "town hall",
              "intersection", "busy area", "apartment", "parking lot", "public park", "downtown area"],
    "under_the_influence": ["under the influence of alcohol", "intoxicated", "drunk", "high",
                            "under the influence", "in an intoxicated state", "impaired"],
    "charged_with": ["charged with", "arrested for", "accused of", "indicted for", "under suspicion of"],
    "conspiracy_to": ["conspiracy to", "planned to", "plotting to", "attempting to", "intended to", "solicitation to",
                      "accessory after the fact to", "aiding and abetting to"],
    "without": ["without", "without", "withou", "not with", "absent of", "lacking", "with no"],
    "reckless": ["dangerous", "careless", "negligent", "reckless", "irresponsible", "unsafe"],
    "invalid": ["suspended", "invalid", "expired", "revoked", "fake", "canceled"],
    "stolen_property": ["property", "handbag", "wallet", "valuables", "electronics", "personal belongings", "jewelry",
                        "merchandise", "goods"],
    "payment_card": ["credit card", "debit card", "payment card", "bank card", "credit card", "atm card"],
    "drug": ["cocaine", "heroin", "marijuana", "drugs", "crack cocaine", "controlled substance",
             "meth", "methamphetamine", "illegal substance", "opioid", "cannabis", "marihuana", "controlled substanc",
             "drug", "marijana", "fentanyl", "narcotic drug"],
    "minor": ["minor", "child", "teen", "15-year-old", "adolescent", "underage person", "child under 15 years of age"],
    "motor_vehicle": ["motorcycle", "car", "motor vehicle", "automobile", "truck", "vehicle", "means of conveyance",
                      "motor vehicle", "auto vehicle"],
    "vehicle_part": ["rear view mirrors", "license plate", "rear lights", "front facing beams", "booster seat",
                     "engine", "plate", "tires", "brakes", "headlights", "tail lights", "brake lights", "equipment",
                     "gear box"],
    "weapon": ["knife", "firearm", "weapon", "gun", "crossbow", "rifle", "lead pipe", "handgun", "deadly weapon",
               "metal knuckle"],
    "firearm": ["firearm", "automatic weapon", "gun", "rifle", "handgun", "automatic rifle", "pistol"],
    "victim": ["bystander", "shopkeeper", "employee", "person", "individual", "victim", "manager"],
    "negligence": ["negligence", "carelessness", "lack of care", "disregard", "omission"],
    "numeric_quantity": ["5", "5 to 10", "15", "45", "50-100", "250", "750", "1000"],
    "resisting": ["resisting", "resisting", "obstructing", "having resisted", "having obstructed", "hindering",
                  "having hindered", "opposing", "refusing"],
    "officer": ["police officer", "law enforcement officer", "law enforcement agent", "police agent", "officer",
                "public servant"],
    "improper": ["improper", "illegal", "unsatisfactory", "unlawful", "prohibited", "wrongful", "banned"],
    "distribute": ["distribute", "sell", "deal", "deliver", "trade", "traffic"],
    "failure to": ["failure to", "did not", "failed to", "neglected to", "omitted to"],
    "assault": ["assault", "battery", "assault", "assault and battery"],
    "prison": ["prison", "jail", "detention center", "correctional facility", "penal facility"],
    "identification": ["identification", "id", "identity", "id card", "personal identification"],
    "intimidating": ["intimidating", "intimidating", "threatening", "terrorizing", "coercing",
                     "menacing"],
    "minor_degree_level": ["second degree", "third degree", "fourth degree", "2nd degree", "3rd degree", "4th degree"],
    "alcoholic_beverage": ["open container", "alcoholic container", "container with alcohol", "bottle of liquor",
                           "can of beer", "bottle of whiskey", "alcoholic beverage", "malt beverage"],
    "deception": ["deception", "misrepresentation", "swindle", "fraud", "trickery", "conning"],
    "fraudulent": ["false", "fictitious", "fabricated", "counterfeit", "forged", "untrue", "fraudulent", "bogus",
                   "fake", "fictitious"],
    "financial_gain": ["financial gain", "monetary gain", "profit", "economic benefit", "financial profit", "money"],
    "fighting": ["fighting", "brawling", "engaging in a fight", "physical altercation", "scuffling"],
    "disturbance": ["disturbance", "disorderly conduct", "unruly behavior", "nuisance",
                    "rowdiness", "disorder", "breach of the peace", "affray"],
    "harassing": ["harassing", "annoying", "bothering", "disturbing", "molesting", "pestering", "shouting insults at",
                  "screaming obscenities at", "taunting", "abusing verbally", "yelling profanities at"],
    "schedule_drug": ["schedule 1", "schedule 2", "schedule 3", "schedule 4", "schedule 5", "schedule 6"],
}


def replace_placeholders(template: str) -> str:
    """
    Replaces any placeholder like {hit}, {light}, {place}, etc. found in the template.
    If a placeholder does not exist in placeholder_options, it is left as-is.
    """
    result = template

    # Identify all placeholders by scanning for curly braces
    # e.g. {hit}, {light}, {place}
    # You can do this more robustly with regex, but here's a simple approach:
    placeholders_found = []
    pattern = re.compile(r"{(.*?)}")
    placeholders_in_text = pattern.findall(template)

    for ph in placeholders_in_text:
        ph_list = placeholder_options.get(ph)
        if ph_list:
            replacement = random.choice(ph_list)
            # Replace all occurrences of this placeholder in the template
            result = result.replace("{" + ph + "}", replacement)

    return result


# Create augmented dataset
def create_dataset(output_file="datasets/samples.csv", samples_per_category=1500):
    with open(output_file, "w", newline="", encoding="utf-8") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["text", "label"])
        total_desired_samples = len(categories) * samples_per_category
        total_templates_count = 0
        for label, templates in categories.items():
            for _ in range(len(templates)):
                total_templates_count += 1
        for label, templates in categories.items():
            category_samples_count = int((len(templates) / total_templates_count) * total_desired_samples)
            print(f"Generating {category_samples_count} examples for {label}...")
            for _ in range(category_samples_count):
                template = random.choice(templates)
                text = replace_placeholders(template)
                if "}" in text or "{" in text:
                    print(f"Warning: Placeholder not replaced in template: {template}")
                writer.writerow([text, label])


# Example usage
if __name__ == "__main__":
    create_dataset("datasets/samples.csv", samples_per_category=1000)  # Adjust as needed
