import csv
import random
import re

# Categories and example templates
categories = {
    "Drug Trafficking": [
        "delivery of {drug}",
        "{drug} for delivery",
        "distributing {drug}",
        "distribution of {drug}",
        "{charged_with} drug trafficking",
        "{charged_with} dealing in {drug}",
        "{charged_with} {drug} dealing",
        "trafficking {drug}",
        "{conspiracy_to} traffic {drug}",
        "transporting {drug}",
        "selling of {drug}",
        "{drug} for sale",
        "{possessing} {drug} for sale",
        "{charged_with} {possessing} {drug} for sale",
        "possession of {drug} with intent to {distribute}",
        "possession of {drug} with intent",
        "possess {drug} intention to {distribute}",
        "carrying {drug} with intention to {distribute}",
        "{possessing} {drug} with purpose to {distribute}",
        "transport {drug} intent to {distribute}",
        "{charged_with} transport of {drug}",
        "selling {drug} by the {place}",
        "carrying {drug} for sale at a {place}",
        "planning to sell {drug} for profit",
        "{charged_with} illegally smuggling {drug} to sell on market",
        "{charged_with} manufacturing {drug}",
        "{charged_with} making {drug} for sale"
    ],
    "Drug Possession": [
        "consume {drug} for personal use",
        "consumption of {drug}",
        "{charged_with} {possessing} {drug} for consumption",
        "smoking {drug} by the {place}",
        "{charged_with} consuming {drug}",
        "possess {drug} for personal use",
        "possess {drug}",
        "{possessing} {drug}",
        "{drug} possession",
        "possession of {drug}",
        "in possession of {drug}",
        "under influence of {drug}",
        "taking {drug}",
        "use of {drug}",
        "using {drug}",
        "carrying {drug}",
        "{charged_with} being under the influence of {drug}",
        "intoxicated by {drug} while working",
        "found at the {place} intoxicated by {drug}",
        "{possessing} {numeric_quantity} grams of {drug}",
        "{charged_with} {drug} possession - {numeric_quantity} grams",
        "{drug} possession, misdemeanor",
    ],
    "Unspecified Drug Offense": [
        "possession of drug paraphernalia",
        "in possession of drug related equipment",
        "hypodermic needle syringe",
        "{charged_with} possession of a hypodermic needle",
        "{possessing} a hypodermic syringe",
        "{possessing} drug paraphernalia",
        "manufacturing drug paraphernalia",
        "using drug paraphernalia",
        "using drug paraphernalia at a {place}",
        "{charged_with} using drug paraphernalia, misdemeanor",
        "{possessing} a injection syringe",
        "using materials to make drugs",
        "{charged_with} possessing paraphernalia for drugs",
        "{charged_with} unspecified {drug} offense"
    ],
    "Unspecified Manslaughter": [
        "killed another person in an incident that remains unclear",
        "responsible for an accidental death without clear intent",
        "involved in a fatal situation where cause was uncertain",
        "killed person in unclear circumstances"
    ],
    "Intimidation (Not Witness)": [
        "{charged_with} intimidation",
        "{severe} intimidation",
        "intimidation of a {victim}",
        "intimidating a {victim}",
        "{charged_with} intimidating a {victim} who is not a witness",
        "intimidating a {victim} {without} a financial motive",
        "threatening a {victim} to instill fear",
        "used force or threats to intimidate a victim",
        "made threatening statements to a {victim}",
        "{charged_with} blackmailing a person",
        "{charged_with} blackmailing {without} demanding money",
        "{charged_with} blackmailing {without} financial gain involved",
        "using threatening language to {family_member}",
        "{charged_with} making threats to an individual",
        "{charged_with} menacing behavior towards a {victim} with credible threat of violence",
        "{charged_with} threatening violence",
        "{conspiracy_to} intimidate a {victim}",
    ],
    "Intimidating a Witness": [
        "{charged_with} intimidating a witness",
        "{severe} intimidation of a court witness",
        "{charged_with} intimidation of a witness during a legal proceeding",
        "intimidating a witness {without} a financial motive",
        "{charged_with} threatening a witness to instill fear",
        "{charged_with} threatened a witness to prevent them from testifying",
        "used coercion to influence the testimony of a witness",
        "made threats to intimidate someone into silence during an investigation",
        "intimidating a witness",
        "{charged_with} witness intimidation",
        "threatening victim to affect testimony",
        "{conspiracy_to} intimidate a witness",
        "pressured a witness to change their statement",
        "warned a witness with harm if they spoke in court",
        "attempted to bribe a witness to remain silent",
        "coerced a {victim} to withdraw a complaint",
        "harassed a potential witness at {place}",
        "stalked a witness to deter them from testifying",
        "sent intimidating messages to a trial witness",
        "displayed a {weapon} while confronting a witness",
        "threatened witness's family to discourage cooperation",
        "offered money to a witness for false testimony",
        "menacing a key witness in a criminal case",
        "attempted to suborn perjury by intimidation",
        "forced a witness to provide misleading statements",
        "accused of terrifying a witness into non-cooperation"
    ],
    "Extortion": [
        "{charged_with} extortion",
        "{conspiracy_to} extort",
        "{severe} extortion",
        "{improper} extortion",
        "extorting a {victim}",
        "threatened to release damaging information unless paid",
        "{charged_with} having blackmailed someone for money",
        "{charged_with} blackmail for financial gain",
        "{charged_with} using threats to obtain financial gain",
        "intimidating a {victim} for the purpose of financial gain",
        "extracted money from a {victim} through threats",
        "{improper} demand of hush money",
        "forced someone to hand over property through threats",
        "demanded payment from {victim} in exchange for withholding incriminating photos",
        "coerced a {victim} into transferring funds under duress",
        "extorted local businesses for protection fees",
        "pressured a {victim} to pay hush money",
        "made menacing phone calls demanding cash",
        "claimed physical harm would come if money was not paid",
        "threatened property damage in exchange for ransom",
        "attempted to extort a wealthy {victim}",
        "threatened public exposure of embarrassing details for money",
        "extracted money through repeated threats of violence"
    ],
    "Burglary": [
        "{charged_with} burglary",
        "{conspiracy_to} commit burglary",
        "{charged_with} breaking and entering",
        "broke into a house and stole a {stolen_property}",
        "forced entry into a building to take {stolen_property}",
        "caught breaking into a private property to steal {stolen_property}",
        "{charged_with} second-degree burglary for entering a residence unlawfully",
        "{charged_with} first-degree burglary after entering a commercial building",
        "{charged_with} burglary after breaking into {place} and taking valuables",
        "entered a house through a window to steal {stolen_property}",
        "used force to gain entry into a home before stealing",
        "burglary incident involving forced entry through a locked door",
        "broke into a storage unit and took items without permission",
        "illegally entered a business at night to steal merchandise",
        "broke into a museum after hours and stole artifacts",
        "burglarized a secure facility and took {stolen_property}",
        "trespassed into a residence to commit theft",
        "{charged_with} burglary after unauthorized entry into {place}",
        "illegally entered a school building with intent to steal",
        "attempted to pry open a locked door to steal property",
        "used tools to break into an apartment and steal electronics",
        "{charged_with} breaking and entering at {place} to commit theft"
    ],
    "Larceny/Motor Vehicle Theft": [
        "{motor_vehicle} theft",
        "{conspiracy_to} commit larceny",
        "petty theft",
        "{charged_with} theft",
        "{charged_with} theft by receiving",
        "received stolen {stolen_property}",
        "{charged_with} theft, misdemeanor",
        "{charged_with} larceny",
        "{possessing} stolen {stolen_property}",
        "{possessing} a stolen {motor_vehicle}",
        "stole a {motor_vehicle} from a parking lot",
        "found driving a stolen {motor_vehicle}",
        "attempting to take a {motor_vehicle} without permission",
        "caught with a stolen {motor_vehicle} in possession",
        "driving a stolen {motor_vehicle}",
        "theft of a {motor_vehicle} from a dealership",
        "shoplifting {stolen_property} from a {place}",
        "grabbed {stolen_property} from a store shelf and ran",
        "took an unattended bag from a table at {place}",
        "stole merchandise without paying at checkout",
        "pick pocketed {stolen_property} from a shopper",
        "switched price tags to steal items from a store",
        "carried unpaid goods past store security",
        "{charged_with} retail theft after taking {stolen_property} from {place}",
        "{charged_with} theft of united states mail",
        "removed security tags from {stolen_property} and walked out of the store",
        "{charged_with} shoplifting after concealing items in clothing",
        "{charged_with} grand theft for stealing high-value {stolen_property}",
        "took a package from someone's porch {without} permission",
        "{charged_with} petty theft after taking a bicycle from a park",
        "{charged_with} theft of property worth $100 in value",
        "{charged_with} theft of services",
        "retail theft of property worth $50 in value",
        "{charged_with} unauthorized use of a {motor_vehicle}",
        "operating a {motor_vehicle} without the owner's permission",
        "{improper} taking of {stolen_property}",
        "{improper} taking of {motor_vehicle}",
        "{improper} taking",
        "{improper} appropriation of {stolen_property}",
        "{charged_with} taking of property",
        "{charged_with} carjacking",
        "{charged_with} carjacking without a weapon",
        "{charged_with} theft {without} having deceived the person",
        "{charged_with} theft but no fraud"
    ],
    "Other Property": [
        "vandalized a private property by spray painting",
        "using graffiti to deface a property",
        "destroyed public property",
        "damaged someone’s belongings during a dispute",
        "caused pecuniary loss",
        "causing damage to property",
        "{severe} vandalism",
        "{severe} property damage valued at $1000",
        "caused damage to {place} worth $300",
        "spraying graffiti",
        "possession of graffiti items",
        "{charged_with} trespass",
        "{charged_with} trespassing",
        "{charged_with} trespassing on {place}",
        "criminal trespass on a private property",
        "{charged_with} criminal trespass on private property",
        "{charged_with} criminal mischief",
        "{charged_with} tampering with property of a {victim}",
        "criminal mischief",
        "{charged_with} hit and run while causing property damage",
        "{charged_with} hit and run while damaging property",
        "{charged_with} leaving the scene of an accident",
        "{charged_with} leaving the scene of an accident not having caused injury",
        "{charged_with} leaving the scene after having caused property damage",
        "leaving the scene of an accident after damaging a {motor_vehicle}",
        "{severe} damage to property"
    ],
    "Court Violation": [
        "{failure to} appear in court for a scheduled hearing",
        "{failure to} appear",
        "{failure to} appear for a court date",
        "{failure to} appear before court",
        "{charged_with} {failure to} comply with court order",
        "{charged_with} {failure to} comply with a protective order",
        "{charged_with} {failure to} make a court appearance",
        "{failure to} register as a sex offender",
        "{charged_with} not registering as a sex offender",
        "{charged_with} non support",
        "{failure to} provide child support as ordered by the court",
        "{charged_with} {failure to} pay child support",
        "violated terms of probation by missing check-ins",
        "disregarded court order to stay away from a victim",
        "criminal contempt of a domestic violence protective order",
        "contempt of court order",
        "bail jumping",
        "not paying bail as agreed in court",
        "being in contempt of court",
        "contempt of court",
        "not abiding by court order",
        "{failure to} pay court-mandated fines on time",
        "{failure to} comply with a restraining order issued by the court",
        "skipped a mandated court-ordered counseling session",
        "violated terms of release by traveling out of state",
        "ignored a subpoena to testify in a legal proceeding",
        "missed compulsory community service ordered by the judge",
        "{failure to} check in with a parole officer as required",
        "ignored a protective order requiring no contact with a {family_member}",
        "attempted to contact a witness despite a court no-contact order",
        "refused to appear for jury duty after being summoned",
        "did not submit court-ordered documentation by the specified deadline",
        "breached the conditions of a plea agreement",
        "attempted to influence a witness in violation of court directives",
        "skipped scheduled drug testing mandated by the court"
    ],
    "Public Order": [
        "{charged_with} littering in a public {place}",
        "littering by a {place}",
        "{severe} littering",
        "{charged_with} {improper} littering",
        "{charged_with} leaving dog at large",
        "{charged_with} not controlling dog by the {place}",
        "{improper} control of dog",
        "{charged_with} ordinance violation",
        "{charged_with} violating local ordinance",
        "shouting obscenities and disturbing the peace in public",
        "engaged in a loud argument in a public {place}",
        "created a disturbance by yelling in a busy {place}",
        "disorderly conduct",
        "breach of the peace",
        "{charged_with} brawling in public",
        "{charged_with} {improper} breach of the peace",
        "{charged_with} causing an affray",
        "participated in a {severe} affray",
        "{charged_with} disorderly conduct on public transport",
        "{charged_with} interfering with an emergency phone call",
        "{improper} loitering and prowling",
        "{charged_with} inducing panic",
        "{charged_with} molesting passerby",
        "{improper} harassment of a {victim}",
        "{charged_with} harassment in a public place",
        "{charged_with} harassment",
        "{charged_with} causing a public nuisance",
        "{failure to} pay fare on public transport",
        "{charged_with} participating in a street gang",
        "{improper} gang activity",
        "{improper} mob action",
        "{failure to} to pay transportation fare",
        "causing a public disturbance",
        "public order offense",
        "{charged_with} disturbing the public order",
        "{failure to} to respect the lawful order",
        "obscene act in public",
        "indecent exposure in public",
        "public intoxication at the {place}",
        "causing chaos by throwing trash in public areas",
        "arguing loudly with a {victim} in a crowd",
        "brawling at {place} causing panic among bystanders",
        "playing extremely loud music near {place}, disturbing residents",
        "disrupting a public event with unruly behavior",
        "aggressively confronting strangers in the street, disturbing public peace"
    ],
    "Rioting": [
        "rioting",
        "looting",
        "unlawful assembly to riot",
        "unlawful protest to riot",
        "conspiracy to riot",
        "intending to riot",
        "planning to riot",
        "burning down shops during a riot",
        "attempted to incite a riot among bystanders",
        "hurling projectiles at law enforcement in a riot",
    ],
    "Alcohol Violation": [
        "{minor} possession of alcohol",
        "{minor} in possession of alcohol",
        "consumption of alcohol under the age limit",
        "{minor} using alcohol",
        "{minor} {under_the_influence}",
        "{minor} {possessing} alcohol",
        "found a {minor} {possessing} alcohol",
        "underage drinking",
        "{minor} found drinking near a {place}",
        "{minor} caught with open containers of alcohol",
        "cited for underage {possessing} of liquor at {place}",
        "found {minor} consuming alcohol near {place}",
        "{minor} discovered heavily intoxicated at {place}",
        "{minor} still {under_the_influence} after leaving a party",
        "police found a {minor} with beer behind a {place}",
        "accused a {minor} of underage {possessing} of alcoholic drinks",
        "{minor} attempted to purchase alcohol at a local store",
        "arrested {minor} for underage drinking near {place}",
        "found {minor} intoxicated near the {place} with open containers",
        "caught a {minor} carrying multiple bottles of alcohol in a backpack",
        "an open container was found in the {motor_vehicle}",
        "an open container is in the {motor_vehicle} but is not the driver's",
        "passenger in a {motor_vehicle} with an open container",
        "{charged_with} possession of an open container",
        "{improper} possession of an open container",
        "open container",
        "{possessing} a container of alcohol which was not closed"
    ],
    "Public Institution Violation": [
        "{charged_with} introducing contraband into a {prison}",
        "{possessing} contraband in a {prison}",
        "{possessing} a prohibited objects in a {prison}",
        "entry into {prison} with {improper} contraband",
        "intending to {distribute} {improper} items in a {prison}",
        "{prison} resident smuggled {improper} items",
        "{charged_with} {possessing} of {improper} items in a {prison}",
        "keeping a {improper} phone while residing at a {prison}",
        "{possessing} contraband while in a {prison}",
        "attempted to bring {improper} items into a {prison}",
        "caught with {improper} items inside a {prison}",
        "attempted to introduce {improper} items into a {prison}",
        "caught with {improper} items inside a {prison}",
        "smuggling {improper} items into a {prison}",
        "smuggling contraband into a {prison}",
        "{conspiracy_to} introduce contraband into a {prison}",
        "{conspiracy_to} smuggle {improper} items into a {prison}",
    ],
    "Illicit Business": [
        "{charged_with} illegal gambling near a {place}",
        "engaged in gambling at the {place}",
        "{improper} gambling",
        "gambling",
        "{improper} wagering while playing cards at {place}",
        "{charged_with} {improper} betting",
        "{charged_with} operating an {improper} gambling den",
        "participating in high-stakes betting {without} permission",
        "involved in an underground gambling ring {without} required permits",
        "detained for organizing illicit gambling events at {place}",
        "suspected of running {improper} gambling activities in {place}",
        "arrested for engaging in covert gambling operations",
        "{improper} betting schemes at {place}",
        "operating a secret gambling network in {place}",
        "implicated in {improper} high-roller gambling events at {place}",
        "witnessed at a clandestine gambling club in {place}",
        "{charged_with} {improper} soliciting of ride share services",
        "{charged_with} {improper} solicitation of rides",
        "{improper} selling of services with {invalid} license",
        "prostitution",
        "{charged_with} soliciting prostitution",
        "{improper} pimping",
        "{charged_with} operating a prostitution business",
        "{charged_with} operating a {improper} brothel"
        "{conspiracy_to} sell immoral services",
    ],
    # "All Other Offenses": [
    #     "failure to pay fare",
    #     "not paying fare on bus",
    #     "failure to pay fare on train",
    #     "not purchasing a ticket",
    #     "jumping the ticket barrier at station",
    #     "conspiracy second degree",
    #     "dumping trash illegally at {place}",
    #     "jaywalking at a busy intersection near {place}",
    #     "littering in a prohibited area near {place}",
    #     "smoking in a non-smoking zone at {place}",
    #     "not following local curfew regulations",
    #     "throwing objects from a moving vehicle",
    #     "fishing without a valid license",
    #     "selling goods without a permit at {place}",
    #     "walking pets off-leash in a restricted area",
    #     "violating a local noise ordinance in a neighborhood",
    #     "refusing to comply with local business regulations",
    #     "operating a business after hours without permission",
    #     "cycling on sidewalks where prohibited",
    #     "failing to clean up after a pet in public"
    # ],
    "Murder": [
        "intentionally killed another person",
        "committed premeditated murder",
        "murdered someone in cold blood",
        "murder",
        "{conspiracy_to} commit murder",
        "premeditated killing",
        "planned killing",
        "murdered {victim}",
        "killed {victim} intentionally",
        "took a life with clear intent at {place}",
        "fatally shot a {victim} with malicious forethought",
        "{charged_with} homicide with prior planning",
        "deliberately ended someone's life at {place}",
        "charged with orchestrating a murder",
        "assassinated a {victim} in a targeted attack",
        "executed a deadly plan against {victim}",
        "plotting and carrying out a homicide",
        "committing a planned homicide on {victim}",
        "accused of intentionally slaying a {victim}",
        "killing a {victim} in a premeditated manner",
        "{charged_with} deliberate homicide at the {place}"
    ],
    "Non-Negligent Manslaughter": [
        "killed {victim} in the heat of the moment",
        "{charged_with} intentionally caused someone’s death during a fight",
        "killed another person in a non-accidental situation",
        "manslaughter",
        "shot someone to death intentionally",
        "intentional manslaughter",
        "fatally injured a {victim} in a spontaneous altercation",
        "death resulted from a sudden conflict with {victim}",
        "emotional outburst leading to the fatality of {victim}",
        "non-accidental homicide classified under manslaughter",
        "a fatal encounter with no prior intent but still purposeful",
        "a violent confrontation leading to {victim}'s death",
        "killed a {victim} amid intense provocation",
        "admitted to causing fatal harm without preplanning",
        "ended the life of a {victim} in a volatile dispute",
        "manslaughter charges for an impulsive killing",
        "unplanned but intentional act causing death",
        "{charged_with} lethally harmed {victim} during a {fight}",
        "offense of killing someone in an emotional rage",
        "accused of manslaughter for a sudden deadly action"
    ],
    "Vehicular Manslaughter": [
        "caused a fatal accident while driving recklessly",
        "killed a pedestrian in a car accident",
        "killed someone through careless driving",
        "hit someone while driving, resulting in death",
        "killed passerby whilst driving",
        "fatally struck a {victim} with a {motor_vehicle}",
        "charged with driving irresponsibly leading to a death",
        "caused a deadly crash at a {place}",
        "took someone's life in a high-speed collision",
        "ran over a {victim} due to {reckless} driving",
        "failed to stop, causing a fatal vehicle accident",
        "{charged_with} negligent operation of a {motor_vehicle} leading to death",
        "killed {victim} in a drunk driving incident",
        "lost control of {motor_vehicle}, causing a fatality",
        "death occurred after colliding with a {victim} on the road",
        "charged with vehicular homicide following an accident",
        "unintentional killing with a {motor_vehicle}",
        "struck a {victim} in a crosswalk causing fatal injuries",
        "indicted for vehicular manslaughter in a {place}",
        "accidentally ended {victim}'s life with reckless operation"
    ],
    "Negligent Manslaughter": [
        "caused death by failing to follow safety precautions",
        "accidentally killed another person by negligence",
        "{charged_with} caused death through negligence",
        "accidentally caused death",
        "death occurred because of {reckless} oversight",
        "lacked due caution leading to fatal incident",
        "{failure to} maintain safe conditions caused a death",
        "unintentionally ended a life by ignoring rules",
        "led to a deadly outcome through carelessness",
        "accidentally caused someone's demise due to lack of attention",
        "a fatal slip-up caused by negligence",
        "bypassed safety measures resulting in a death",
        "forgot essential precautions leading to someone's death",
        "negligently handled equipment causing fatality",
        "responsible for a death due to omission of care",
        "accidentally ended the life of {victim} through incompetent actions",
        "unintentional killing tied to disregard for safety",
        "{charged_with} failing to prevent hazards resulted in a death",
        "did not foresee obvious risks leading to fatality",
        "neglected standard safety protocols, causing fatal outcome"
    ],
    "Kidnapping": [
        "false imprisonment of a {victim}",
        "false imprisonment of a {minor}",
        "{severe} kidnap",
        "{improper} imprisonment",
        "{improper} confinement",
        "{improper} abduction",
        "{charged_with} abducting a {victim} against their will",
        "held someone hostage for ransom",
        "{charged_with} abduction",
        "{charged_with} kidnapping",
        "abducting an individual",
        "{charged_with} kidnapping and hiding a person",
        "kidnap of a person",
        "abducting an individual",
        "unlawful confinement of a {victim} in a secret location",
        "forcing a {victim} into a {motor_vehicle} against their will",
        "seizing control of someone's movements without permission",
        "detaining a {victim}",
        "taking a {victim} under threat from the {place}",
        "coercing {victim} into captivity",
        "snatching a {victim} from public space",
        "detaining a {victim} for illegal reasons",
    ],
    "Child Abuse": [
        "child abuse",
        "{charged_with} physically harming a child",
        "{inflicted} {severe} harm to a child",
        "neglected a child’s well-being causing harm",
        "abused a {minor} mentally and physically",
        "{inflicted} {severe} child abuse",
        "{strangled} a child",
        "shown {negligence} towards a {minor}",
        "{charged_with} {reckless} child endangerment",
        "{charged_with} repeatedly abusing a child",
        "having abused a child at home",
        "{severe} abuse of a child",
        "causing {severe} harm to a child",
        "abused a child physically but not sexually",
        "{charged_with} physically harming a child but not sexually"
    ],
    "Forcible Sex Offense": [
        "{raped} an individual by force",
        "sexual assault of a person using violence",
        "forcibly {raped} another adult at the {place}",
        "{raped} {victim} against their will",
        "{raped} {victim} at {place}",
        "forced someone into non-consensual sexual activity",
        "{raped} another adult by force",
        "{charged_with} sexual violence",
        "{charged_with} rape",
        "{charged_with} rape at a {place}",
        "{severe} sexual assault",
        "{charged_with} rape of adult",
        "{charged_with} intention to assault sexually",
        "intent to sexually assault",
        "forcible sex offense",
        "{charged_with} sexual battery",
        "{charged_with} forcible sex offense at {place}",
        "rape of a {minor}",
        "engaged in sexual relations with a {minor}",
        "{possessing} child pornography",
        "{charged_with} {possessing} child pornography on their hard drive",
        "{possessing} pornographic material of a {minor}",
        "{possessing} pornographic images of a {minor}",
        "found {possessing} pornographic images of children",
        "{possessing} explicit images of a {minor}",
        "{charged_with} {possessing} indecent images of a {minor}",
        "communication with a {minor} for immoral purposes",
        "texting a {minor} for immoral reasons",
        "having sent texts to a {minor} for sexual reasons",
        "{charged_with} having communicated with a {minor} with improper intentions",
        "{conspiracy_to} commit rape"
    ],
    "Aggravated Assault": [
        "aggravated assault",
        "{severe} assault",
        "{severe} assault led to bodily harm",
        "{charged_with} assault causing bodily injury",
        "{charged_with} aggravated assault",
        "{severe} domestic {assault} with bodily injury",
        "{charged_with} {severe} {assault}",
        "domestic {assault} causing injuries to body",
        "{assault} on {family_member} causing injuries",
        "{strangled} {victim} with a rope causing {severe} injuries",
        "{severe} {assault} involving a {weapon}",
        "{assault} with a {firearm}",
        "used a {weapon} to seriously harm a person",
        "{strangled} with a {weapon} causing severe injury",
        "severely {strangled} someone during a {fight}",
        "strangulation leading to loss of consciousness",
        "{inflicted} {severe} injury requiring hospitalization",
        "{strangled} an individual severely leading to medical attention",
        "{severe} beating of an individual resulting in broken bones",
        "{strangled} {victim} causing {severe} injury requiring surgery",
        "{strangled} {family_member} in a violent domestic altercation",
        "{charged_with} {inflicted} {severe} injury leading to long-term damage",
        "{severe} aggravated {assault} using a {weapon}",
        "{severe} aggravated {assault} using a {firearm}",
        "{assault} causing bodily injury requiring emergency treatment",
        "first-degree assault leading to permanent disfigurement",
        "assault causing {severe} harm and life-threatening injuries",
        "{charged_with} {assault} with a deadly {weapon} at {place}",
        "{strangled} a {victim} until they nearly lost consciousness",
        "used excessive force to {assault} {victim} causing critical injuries",
        "{assault} resulted in severe bodily trauma needing ICU treatment"
    ],
    "Simple Assault": [
        "{charged_with} {assault}",
        "simple {assault}",
        "{assault}, misdemeanor",
        "{assault} {without} bodily harm",
        "{charged_with} {assault} {without} bodily injury",
        "{charged_with} domestic abuse",
        "{assault} on {family_member}",
        "domestic {assault}",
        "domestic {assault} {without} injury caused",
        "{assault} on a {family_member} {without} body injury",
        "{charged_with} domestic violence",
        "{assault} {without} a {weapon}",
        "{assault} in the second degree",
        "{charged_with} simple {assault}",
        "{charged_with} domestic {assault}",
        "{charged_with} minor {assault}",
        "{light} {assault}",
        "{assault} on a {officer}",
        "resisting an {officer} with {severe} violence",
        "violently resisted arrest by an {officer}",
        "{hit} an officer who was arresting them",
        "{charged_with} having {hit} a {officer} during arrest",
        "{assault} - third degree",
        "{charged_with} {assault} in the fourth degree",
        "{assault} in the fourth degree causing a {light} injury",
        "{hit} someone in a {light} {fight} but caused no serious harm",
        "{hit} a {victim} during a {fight} resulting in {light} bruising",
        "pushed a {victim} in an argument without major injury",
        "{inflicted} {light} bruises during a heated altercation",
        "got into a {fight} and shoved a person causing {light} injuries",
        "{assault} causing {light} injury but no hospitalization",
        "{hit} employee causing {light} bruising no medical treatment needed",
        "{hit} {victim} causing {light} discomfort but no severe harm",
        "minor altercation with {victim} resulting in {light} scratch",
        "verbal dispute escalated to {hit} but no major injuries occurred",
        "{charged_with} simple {assault} after pushing {victim} at {place}",
        "argument led to a {fight} resulting in minor injuries only"
    ],
    "Weapons Offense": [
        "{possessing} a firearm {without} a permit",
        "possessed a {weapon} illegally",
        "{improper} possession of a regulated {firearm}",
        "recklessly wielding a {weapon}",
        "regulated {weapon} illegal possession",
        "{improper} possession of a regulated {weapon}",
        "{charged_with} {possessing} a {weapon}",
        "{possessing} a {firearm} with an {invalid} license",
        "{charged_with} unregistered {firearm}",
        "{possessing} a {firearm} without a license",
        "possession of {weapon} {without} authorization",
        "felon in possession of a weapon",
        "{possessing} a {weapon} as a convicted felon",
        "violent felon {possessing} a {weapon}",
        "wearing and carrying an unconcealed {weapon}",
        "{improper} storage of a {firearm}",
        "{charged_with} weapons offense",
        "{improper} use of a {weapon}",
        "{charged_with} not properly storing a {weapon}",
        "{possessing} an {invalid} weapons license",
        "{charged_with} {possessing} a {firearm} {without} a valid permit",
        "{charged_with} possession of a {weapon} without required registration",
        "{charged_with} unlawful carrying of a concealed {firearm}",
        "illegal possession of a {weapon} by a prohibited person",
        "{charged_with} having an unlicensed firearm in a public space",
        "felon found in possession of a restricted {weapon}",
        "{charged_with} carrying a {weapon} in a prohibited area",
        "{charged_with} improper storage of a {weapon}, violating safety laws",
        "attempted to purchase a {firearm} illegally",
        "{charged_with} possession of high-capacity magazines in violation of the law",
        "{charged_with} failure to report a lost or stolen {weapon}",
        "{charged_with} unlawful sale of ammunition"
        "{charged_with} {improper} sale of ammunition",
        "{improper} weapons trafficking"
    ],
    "Robbery": [
        "{severe} robbery",
        "{charged_with} robbery",
        "armed carjacking",
        "held up a store at gunpoint demanding money",
        "took {stolen_property} at gunpoint from a cashier",
        "seized {stolen_property} with a knife during a robbery",
        "brandished a {weapon} while demanding valuables",
        "used a firearm to threaten a {victim} into handing over {stolen_property}",
        "pointed a gun at a {victim} and demanded their wallet",
        "threatened a {victim} with a {weapon} while demanding money",
        "committed a violent mugging stealing {stolen_property} from a passerby",
        "robbed a bank teller while wielding a {weapon}",
        "stole {stolen_property} from a store clerk under threat of force",
        "forcibly took {stolen_property} from a {victim} at {place}",
        "used physical violence to rob {stolen_property} from a person",
        "robbed a convenience store by threatening the cashier",
        "carjacked a {motor_vehicle} at gunpoint from its owner",
        "assaulted and robbed a pedestrian near {place}",
        "threatened to harm a bank employee unless they handed over cash",
        "{charged_with} armed robbery after brandishing a gun at a store",
        "{charged_with} attempted robbery for trying to snatch a purse at knifepoint",
        "attempted to rob a jewelry store but was stopped by security",
        "{charged_with} conspiracy to commit robbery at a bank",
        "{charged_with} committing aggravated robbery at {place}",
        "{charged_with} attempting to rob a gas station clerk",
        "{charged_with} home invasion robbery"
    ],
    "Hit and Run with Bodily Injury": [
        "hit {victim} with a car and fled the scene",
        "caused an accident and left the {victim} injured without providing help",
        "drove away after hitting a {victim} on a crosswalk",
        "ran from scene after causing injury",
        "attacked {victim} and ran away",
        "escaped after injuring person",
        "causing injury to {victim} and fleeing",
        "failed to stop after striking a cyclist, leaving them hurt",
        "fled the scene following a collision causing bodily harm",
        "recklessly hit {victim} with {motor_vehicle} then evaded authorities",
        "indicted for hit-and-run leading to injuries",
        "{charged_with} knocked over a pedestrian and drove off",
        "driver left the scene after an injurious crash",
        "did not render aid after colliding with {victim}",
        "struck a {victim} crossing the street and failed to remain",
        "skipped out on the accident scene leaving injuries behind",
        "absconded immediately after harming a {victim}",
        "hit {victim} near {place} and didn't stop",
        "recklessly caused harm in an accident before fleeing the site"
    ],
    "Other Violent Offense": [
        "{reckless} endangerment",
        "{charged_with} endangering other people",
        "{charged_with} {reckless} endangerment",
        "{improper} causing of danger",
        "{charged_with} dangerous conduct",
        "{charged_with} deadly conduct",
        "posing a {severe} risk to safety",
        "wanton endangerment",
        "{charged_with} dangerously throwing a missile",
        "throwing a projectile at a {motor_vehicle}",
        "{severe} throwing of objects",
        "launching a missile at a {motor_vehicle}",
        "hurling a rock at a {place}",
        "{charged_with} {reckless} discharging of a {firearm}",
        "{charged_with} discharging a {firearm} in a busy area",
        "{charged_with} {reckless} endangerment with a {firearm}",
        "{charged_with} discharging a {firearm} but no injuries",
        "shooting a {firearm} but not hitting anyone",
        "causing unnecessary danger to others at a {place}",
        "{charged_with} throwing an object at a train",
        "{severe} terrorism",
        "{charged_with} street terrorism"
    ],
    "Arson": [
        "set fire to a building intentionally",
        "burned down a property as an act of vandalism",
        "caused a fire to destroy someone’s belongings",
        "arson",
        "ignited a structure at {place} with malicious intent",
        "started a blaze in a {place} for destructive purposes",
        "{charged_with} deliberately lighting a fire damaging public property",
        "attempted arson by pouring flammable liquid around a house",
        "used an accelerant to spark a blaze at {place}",
        "arrested for trying to burn {victim}'s possessions",
        "torched a vehicle to cause damage",
        "committed arson on a vacant building",
        "suspected of intentionally setting flames in {place}",
        "created a controlled burn that spread unlawfully",
        "plotted to destroy property through fire at {place}",
        "firebombed a garage in a revenge attack",
        "accused of reckless burning endangering the community",
        "setting multiple fires in a spree of arson",
        "attempted to torch a business for insurance fraud",
        "caused extensive fire damage to a {place}"
    ],
    "Fraud": [
        "{charged_with} committing financial fraud by falsifying documents",
        "engaged in {severe} identity theft for financial gain",
        "defrauded a {victim} out of money through false promises",
        "{improper} use of payment card under $1,500",
        "{charged_with} fraudulent use of a credit card",
        "fraud",
        "{conspiracy_to} impersonate another",
        "{improper} impersonation",
        "{conspiracy_to} commit fraud",
        "fraudulent use of a card",
        "defrauded a {victim}",
        "fabricated insurance claims for profit",
        "used counterfeit currency at {place}",
        "submitted fraudulent tax returns",
        "{charged_with} unlawfully claimed government benefits using false information",
        "operated a credit card scam at {place}",
        "fraudulently used a stolen debit card to make a purchase",
        "{charged_with} retail fraud",
        "{charged_with} criminal conversion of {stolen_property}",
        "{charged_with} theft by check of a {victim}",
        "theft of check",
        "{charged_with} theft of check of a {victim}",
        "{charged_with} {improper} theft of {identification}",
        "{severe} {identification} theft",
        "{charged_with} using another person's {identification} for criminal purposes",
        "{improper} use of another person's {identification}",
        "{improper} use of a {victim}'s {identification}",
        "{improper} use of false {identification}",
        "use of another person's {identification} without permission",
        "{charged_with} stealing of {identification} for {improper} purpose",
        "fraudulent use of someone else's {identification}",
        "{charged_with} fraudulent use of a telephone",
        "{possessing} stolen {identification} that is not their own",
        "{possessing} {identification} to commit forgery",
        "{possessing} forged instruments",
        "{possessing} forged bank bills",
        "{improper} forgery of documents",
        "fabricated {improper} documents to deceive {victim}",
        "falsifying paperwork to purchase a {weapon}",
        "falsifying paperwork to purchase a {motor_vehicle}",
        "{possessing} forged documents to purchase a {weapon}",
        "{charged_with} making false statement to purchase a firearm",
        "{charged_with} falsifying statement to purchase a {motor_vehicle}",
        "{charged_with} making a false statement for a purchase",
        "{charged_with} theft by deception",
        "stealing from a {victim} by deceiving them",
        "{charged_with} theft using deceptive means"
    ],
    "Embezzlement": [
        "{charged_with} embezzlement",
        "{improper} embezzlement",
        "{charged_with} {improper} use of funds trusted to them",
        "{charged_with} misappropriation of funds",
        "misappropriated company resources for personal use",
        "embezzled money from a non-profit organization",
        "embezzled funds",
        "embezzlement",
        "converted employer’s assets for personal benefit",
        "took {victim}'s money entrusted for safekeeping",
        "diverted corporate funds to private accounts",
        "{charged_with} fraudulently using company credit cards for personal expenses",
        "embezzled petty cash from the office",
        "doctoring financial statements to hide misappropriations",
        "skimmed profits from daily sales",
        "exploited position to siphon organizational funds",
        "pocketed charity donations for personal gain",
        "laundered misappropriated funds through shell accounts",
        "failed to deposit client payments into official accounts",
        "abused trust by transferring money to personal account",
        "secretly withdrew money from company funds",
        "alleged to have rerouted finances to personal bank",
        "stole payroll checks from employees under supervision"
    ],
    "Escape/Flight": [
        "escaped from lawful custody",
        "{severe} fleeing and eluding {officer}",
        "{charged_with} fleeing and eluding an {officer}",
        "attempted to flee from police during an arrest",
        "broke free from {prison} or detention",
        "{charged_with} evading arrest or detention",
        "escape/flight",
        "{charged_with} fleeing, misdemeanor",
        "{charged_with} eluding",
        "{charged_with} escape or flight",
        "{improper} escape from a {prison}",
        "{improper} fleeing from {officer} while being detained",
        "attempt to run from a {officer}",
        "flight from {officer}",
        "{charged_with} evading an {officer}",
        "ran away from officers",
        "{charged_with} running from {officer}",
        "escaped from a courthouse before sentencing",
        "fled following a traffic stop to avoid arrest",
        "bolted from an {officer} while in handcuffs",
        "ran away from {place} to evade arrest",
        "evaded law enforcement near a busy {place}",
        "attempted to escape while being transported in a police van",
        "slipped out of custody during a {fight} at the station"
    ],
    "Resisting Arrest": [
        "{resisting} arrest",
        "{resisting} arrest by police",
        "{light} {resisting} arrest by an {officer}",
        "resist arrest",
        "{resisting} an {officer} without violence",
        "obstructing being put under arrest by a {officer}",
        "{resisting} apprehension",
        "{resisting} a {officer}",
        "{resisting} {officer}, misdemeanor",
        "having resisted arrest",
        "{resisting} being placed in custody",
        "{charged_with} {resisting} being placed in custody by a {officer}",
        "{charged_with} having resisted arrest",
        "resisted capture at {place} following arrest",
        "{charged_with} having resisted arrest with no violence",
        "{resisting} apprehension by an {officer} without resort to violence",
        "{resisting} arrest but no violence"
    ],
    "Obstructing Justice": [
        "{failure to} identify to an {officer}",
        "{charged_with} giving false {identification} to an {officer}",
        "gave false {identification} to an {officer}",
        "gave false {identification}",
        "{failure to} give {identification}, misdemeanor",
        "falsified their own {identification} to an {officer}",
        "{charged_with} inventing their own {identification} to an {officer}",
        "fugitive failed to identify to an {officer}",
        "{failure to} id fugitive",
        "{failure to} give correct {identification}",
        "{charged_with} {failure to} identify fugitive",
        "{charged_with} giving false information to an {officer}",
        "gave false information on a report to an {officer}",
        "intentionally lied to an {officer} during an investigation",
        "{failure to} give true name to an {officer}",
        "{charged_with} obstruction of justice",
        "obstruction of justice",
        "{charged_with} making a false statement",
        "{charged_with} making a false statement for no particular purpose",
        "{improper} giving of fictitious information to an {officer}",
        "{improper} tampering with evidence at the {place}",
        "{charged_with} tampering with official records",
        "destroyed evidence",
        "{charged_with} obstructing the legal process",
        "{charged_with} destruction of evidence",
        "tampered with evidence while an {officer} was investigating",
        "{failure to} comply with {officer} instructions",
        "{failure to} comply",
        "{failure to} comply with an {officer}'s investigation",
        "{charged_with} interfering with official acts by an {officer}",
        "wasting the time of an {officer}",
        "{charged_with} misusing a 911 call",
    ],
    "Traffic Driving": [
        "speeding near a {place}",
        "operating a {motor_vehicle} in a {improper} manner"
        "driving above the speed limit",
        "driving while {improper}",
        "{charged_with} speeding",
        "{charged_with} driving at {improper} speeds",
        "took part in a race with in the middle of a busy street",
        "drove in speed competition by the {place}",
        "{charged_with} participating in a speeding contest on the roads by the {place}",
        "{charged_with} vehicle speeding",
        "speeding in a {motor_vehicle} outside the {place}",
        "{reckless} driving",
        "driving in a {reckless} way",
        "{charged_with} {reckless} driving",
        "{reckless} operation of a {motor_vehicle}",
        "{charged_with} following {motor_vehicle} too closely",
        "traffic offense",
        "{charged_with} driving past red light by the {place}",
        "{charged_with} failure to stop at a stop sign",
        "owner of {motor_vehicle} did not signal before turning",
        "failure of driver to signal when turning their {motor_vehicle}",
        "failed to signal",
        "{failure to} comply with speed limit at a {place}",
        "{improper} parking",
        "parking in a {improper} place",
        "{charged_with} parking violation",
        "{improper} passing of another {motor_vehicle}",
        "{improper} passing of a yellow line",
        "{improper} texting {without} hands free cell phone while driving",
        "operating a {motor_vehicle} whilst texting on a cell phone",
        "operators and chauffeurs must have be licensed",
        "{failure to} control a {motor_vehicle}",
        "{motor_vehicle} operator failed to control",
        "{motor_vehicle} nuisance"
    ],
    "Traffic Vehicle": [
        "inoperable license tag light",
        "{improper} tag",
        "license plate light not working on {motor_vehicle}",
        "{vehicle_part} not functioning",
        "inoperable {vehicle_part} on {motor_vehicle}",
        "{charged_with} {vehicle_part} violation",
        "{charged_with} using {invalid} plates",
        "{charged_with} display plates of another",
        "{motor_vehicle} license plate light was not switched on",
        "{motor_vehicle}'s rear lights not functioning",
        "{motor_vehicle} lights not working",
        "{motor_vehicle} lights were not functioning",
        "{failure to} wear seat belt",
        "{failure to} dim {motor_vehicle} lights",
        "seat belt violation",
        "{motor_vehicle} owner was not wearing seat belt",
        "was not wearing a safety belt while operating {motor_vehicle}",
        "booster seat violation",
        "all passengers did not have their safety belts on in the {motor_vehicle}",
        "{charged_with} not wearing a seat belt",
        "{charged_with} failing to wear a seat belt while driving"
    ],
    "Traffic Paperwork": [
        "{charged_with} driving under a {invalid} licence",
        "{charged_with} driving under suspension",
        "driving on {invalid} license and privilege",
        "driving {without} a valid license",
        "driving {without} insurance",
        "{without} insurance",
        "{charged_with} driving while barred",
        "barred from operating a {motor_vehicle}",
        "unlicensed operation of a {motor_vehicle}",
        "driving with {invalid} license",
        "insurance {invalid}",
        "insurance that has been revoked",
        "insurance violation",
        "{without} operator's license",
        "driving on a {invalid} license",
        "no driver's license",
        "{failure to} show license to an {officer}",
        "{failure to} register a {motor_vehicle}",
        "{failure to} show driver's license or identification",
        "failure of {motor_vehicle} owner to maintain insurance",
        "{without} valid driving licence",
        "{charged_with} operating a {motor_vehicle} without a license",
        "driving a {motor_vehicle} {without} insurance by the {place}",
        "driving while license {invalid} or {invalid}",
        "driving while {invalid}/revoked",
        "{invalid} registration plate on {motor_vehicle}",
        "driving {motor_vehicle} with an {invalid} registration plate",
        "permitted another to drive a {motor_vehicle} with an {invalid} license",
        "{charged_with} allowing an unlicensed {family_member} to operate a {motor_vehicle}",
        "{failure to} show financial responsibility documentation",
        "{charged_with} {failure to} maintain financial responsibility",
        "{failure to} provide financial responsibility of driver",
        "operating a {motor_vehicle} without required financial responsibility",
        "financial responsibility law"
    ],
    "DUI": [
        "driving under the influence of alcohol",
        "driving with a {improper} blood alcohol content and license suspended",
        "{improper} blood alcohol content of {numeric_quantity}%",
        "driving a {motor_vehicle} with a high blood alcohol content",
        "{charged_with} blood alcohol content over the legal limit",
        "{motor_vehicle} operator refused to take a blood alcohol content test",
        "driving while {under_the_influence}",
        "driving while {under_the_influence} so license was revoked",
        "{severe} driving {under_the_influence}",
        "driving while seriously {under_the_influence}",
        "operating a {motor_vehicle} while {under_the_influence}",
        "{charged_with} driving a {motor_vehicle} while {under_the_influence}",
        "driving a {motor_vehicle} while {under_the_influence} near a {place}",
        "drink driving outside a {place}",
        "{charged_with} driving whilst {under_the_influence}",
        "consuming alcohol while operating a {motor_vehicle}",
        "using alcohol while driving a {motor_vehicle}",
        "{charged_with} {possessing} alcohol while driving by a {place}",
        "{under_the_influence} driving",
        "consuming a {drug} while driving by the {place}",
        "impaired while driving a {motor_vehicle}",
        "operation of a {motor_vehicle} while {under_the_influence}",
        "the driver's open container was found in the {motor_vehicle}",
        "{charged_with} operating a {motor_vehicle} with the driver drinking from an open container",
        "{motor_vehicle} operator {possessing} an open container",
        "{motor_vehicle} operator {possessing} an alcoholic container which is not closed",
        "{motor_vehicle} operator {possessing} an alcoholic container which does not belong to the passenger"
        "driving while {under_the_influence} with a {minor} in the {motor_vehicle}",
        "driving while {under_the_influence} with {family_member} in the {motor_vehicle}",
    ],
    "Immigration": [
        "{charged_with} reentry after deportation",
        "{improper} reentry of removed alien",
        "{improper} reentry",
        "entered the country illegally",
        "violated immigration laws by overstaying a visa",
        "assisted someone in evading immigration authorities",
        "{improper} entry without inspection at the border",
        "{improper} entry into the usa",
        "{improper} entry into the united states",
        "transporting {improper} aliens",
        "{improper} alien",
        "smuggling immigrants",
        "immigration offense",
        "{improper} crossing at border",
        "aided {improper} entry into the usa",
        "evaded border security",
        "{charged_with} evasion of border {officer}"
        "smuggling of migrants",
        "{improper} migration",
        "crossed border without proper documentation",
        "harbored undocumented individuals at a {place}",
        "smuggled migrants across the united states border",
        "arrived at port of entry with an invalid visa"
    ]
}

# Dictionary of possible replacements for placeholders
placeholder_options = {
    "hit": ["slapped", "hit", "punched", "fought", "punching", "scuffled", "shoved", "pushed"],
    "light": ["light", "minor", "negligible", "small", "tiny", "insignificant", "mild"],
    "fight": ["fight", "altercation", "heated argument", "heated exchange", "argument", "scuffle"],
    "inflicted": ["inflicted", "caused", "imposed", "resulted in", "brought about"],
    "family_member": ["spouse", "ex spouse", "family member", "wife", "husband", "girlfriend",
                      "sister", "mother"],
    "raped": ["raped", "sexually assaulted", "forcing sex on", "assaulting sexually"],
    "strangled": ["choked", "strangled", "beat", "attacked", "assaulted", "stabbed", "punched unconscious"],
    "severe": ["severe", "aggravated", "serious", "major", "life-threatening", "extreme", "grievous"],
    "possessing": ["possessing", "using", "having", "in possession of", "owning", "carrying", "found with"],
    "place": ["school zone", "library", "courthouse", "shopping street", "main street", "town hall",
              "intersection", "busy area", "apartment", "parking lot", "public park", "downtown area"],
    "under_the_influence": ["under the influence of alcohol", "intoxicated", "drunk", "high",
                            "under the influence", "in an intoxicated state", "impaired"],
    "charged_with": ["charged with", "arrested for", "accused of", "indicted for", "under suspicion of"],
    "conspiracy_to": ["conspiracy to", "planned to", "plotting to", "attempting to", "intended to"],
    "without": ["without", "not with", "absent of", "lacking"],
    "reckless": ["dangerous", "careless", "negligent", "reckless", "irresponsible", "unsafe"],
    "invalid": ["suspended", "invalid", "expired", "revoked", "fake", "canceled"],
    "stolen_property": ["property", "handbag", "wallet", "valuables", "electronics", "personal belongings", "jewelry"],
    "drug": ["cocaine", "heroin", "marijuana", "drugs", "crack cocaine", "controlled substance",
             "meth", "methamphetamine", "illegal substance", "opioid", "cannabis", "marihuana", "controlled substanc",
             "drug", "marijana", "fentanyl", "narcotic drug"],
    "minor": ["minor", "child", "teen", "15-year-old", "adolescent", "underage person", "child under 15 years of age"],
    "motor_vehicle": ["motorcycle", "car", "motor vehicle", "automobile", "truck", "vehicle", "means of conveyance",
                      "motor vehicle", "auto vehicle"],
    "vehicle_part": ["rear view mirrors", "license plate", "rear lights", "front facing beams", "booster seat",
                     "engine", "plate", "tires", "brakes", "headlights", "tail lights", "brake lights"],
    "weapon": ["knife", "firearm", "weapon", "gun", "crossbow", "rifle", "lead pipe", "handgun", "deadly weapon"],
    "firearm": ["firearm", "automatic weapon", "gun", "rifle", "handgun", "automatic rifle", "pistol"],
    "victim": ["bystander", "shopkeeper", "employee", "person", "individual", "victim", "manager"],
    "negligence": ["negligence", "carelessness", "lack of care", "disregard", "omission"],
    "numeric_quantity": ["one", "5", "5 to 10", "15", "thirty", "45", "fifty five", "50-100"],
    "resisting": ["resisting", "resisting", "obstructing", "having resisted", "having obstructed", "hindering",
                  "having hindered", "opposing", "refusing"],
    "officer": ["police officer", "law enforcement officer", "law enforcement agent", "police agent", "officer",
                "public servant"],
    "improper": ["improper", "illegal", "unsatisfactory", "unlawful", "prohibited", "wrongful", "banned"],
    "distribute": ["distribute", "sell", "deal", "deliver", "trade", "traffic"],
    "failure to": ["failure to", "did not", "failed to", "neglected to", "omitted to"],
    "assault": ["assault", "battery", "assault", "assault and battery"],
    "prison": ["prison", "jail", "detention center", "correctional facility", "penal facility"],
    "identification": ["identification", "id", "identity", "id card", "personal identification"]
}


def replace_placeholders(template: str) -> str:
    """
    Replaces any placeholder like {hit}, {light}, {place}, etc. found in the template.
    If a placeholder does not exist in placeholder_options, it is left as-is.
    """
    result = template

    # Identify all placeholders by scanning for curly braces
    # e.g. {hit}, {light}, {place}
    # You can do this more robustly with regex, but here's a simple approach:
    placeholders_found = []
    pattern = re.compile(r"{(.*?)}")
    placeholders_in_text = pattern.findall(template)

    for ph in placeholders_in_text:
        ph_list = placeholder_options.get(ph)
        if ph_list:
            replacement = random.choice(ph_list)
            # Replace all occurrences of this placeholder in the template
            result = result.replace("{" + ph + "}", replacement)

    return result


# Create augmented dataset
def create_dataset(output_file="datasets/samples.csv", samples_per_category=1500):
    with open(output_file, "w", newline="", encoding="utf-8") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["text", "label"])
        for label, templates in categories.items():
            print(f"Generating {samples_per_category} examples for {label}...")
            for _ in range(samples_per_category):
                template = random.choice(templates)
                text = replace_placeholders(template)
                if "}" in text or "{" in text:
                    print(f"Warning: Placeholder not replaced in template: {template}")
                writer.writerow([text, label])


# Example usage
if __name__ == "__main__":
    create_dataset("datasets/samples.csv", samples_per_category=1000)  # Adjust as needed
